// Midway recipes are manually added post PCWJ to make recipes more sensible and
// introduce new steps to the existing, converted recipes. They're in a separate
// place for now because the converted recipes are autogenerated and we don't
// want them to be overwritten.

/datum/cooking/recipe/torilla
	container_type = /obj/item/reagent_container/cooking/pan
	product_type = /obj/item/reagent_container/food/snacks/tortilla
	catalog_category = COOKBOOK_CATEGORY_BREAD
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/reagent_container/food/snacks/doughslice),
		PCWJ_USE_STOVE(J_LO, 10 SECONDS),
	)

/datum/cooking/recipe/cooked_patty
	container_type = /obj/item/reagent_container/cooking/grill_grate
	product_type = /obj/item/reagent_container/food/snacks/meat/patty
	catalog_category = COOKBOOK_CATEGORY_MEAT
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/reagent_container/food/snacks/meat/patty_raw),
		PCWJ_ADD_REAGENT("sodiumchloride", 1, optional = TRUE),
		PCWJ_USE_GRILL(J_LO, 10 SECONDS),
	)

/datum/cooking/recipe/cooked_meatball
	container_type = /obj/item/reagent_container/cooking/grill_grate
	product_type = /obj/item/reagent_container/food/snacks/meatball
	catalog_category = COOKBOOK_CATEGORY_MEAT
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/reagent_container/food/snacks/rawmeatball),
		PCWJ_ADD_REAGENT("sodiumchloride", 1, optional = TRUE),
		PCWJ_USE_GRILL(J_LO, 10 SECONDS),
	)

/datum/cooking/recipe/taco
	container_type = /obj/item/reagent_container/cooking/board
	product_type = /obj/item/reagent_container/food/snacks/taco
	catalog_category = COOKBOOK_CATEGORY_MEAT
	steps = list(
		PCWJ_ADD_ITEM(/obj/item/reagent_container/food/snacks/tortilla),
		PCWJ_ADD_ITEM(/obj/item/reagent_container/food/snacks/cutlet),
		PCWJ_ADD_ITEM(/obj/item/reagent_container/food/snacks/cheesewedge),
	)
