// ----- Encryption Punch Cards -----

/obj/item/paper/punch_card
	name = "\improper Weyland-Yutani punch card"
	desc = "A stiff piece of paper starting to yellow with a bunch of numbers on it."
	icon_state = "punchcard"
	extra_stylesheets = list("punchcard"="html/browser/punchcard.css")
	/// The asset in /datum/asset/simple/paper for the punch card visuals corresponding to the company that produced it
	var/punch_card_asset = "wy_punch_card.png"
	/// The punched out numbers on this card, though if null can be used for restocking
	var/list/data
	/// The base type of this punch_card for printers to know what type is loaded even when handling subtypes
	var/base_type = /obj/item/paper/punch_card

/obj/item/paper/punch_card/hyperdyne
	name = "\improper Hyperdyne punch card"
	punch_card_asset = "hd_punch_card.png"
	icon_state = "punchcard_hyperdyne"
	base_type = /obj/item/paper/punch_card/hyperdyne

/obj/item/paper/punch_card/Initialize(mapload, photo_list)
	. = ..()

	var/datum/asset/asset = get_asset_datum(/datum/asset/simple/paper)
	extra_headers = list("<style>td.punched{background-image: url('[asset.get_url_mappings()["punch_card_punch.png"]]');}</style>")
	info = "<div class='punchcard-container'>\
		<img class='punchcard' src='[asset.get_url_mappings()[punch_card_asset]]'>\
		<table class='punchcard'>\
		<tr class='punchcard' /><td class='punchslot cell-1-10' /><td class='punchspacer' /><td class='punchslot cell-1-9' /><td class='punchspacer' /><td class='punchslot cell-1-8' /><td class='punchspacer' /><td class='punchslot cell-1-7' /><td class='punchspacer' /><td class='punchslot cell-1-6' /><td class='punchspacer' /><td class='punchslot cell-1-5' /><td class='punchspacer' /><td class='punchslot cell-1-4' /><td class='punchspacer' /><td class='punchslot cell-1-3' /><td class='punchspacer' /><td class='punchslot cell-1-2' /><td class='punchspacer' /><td class='punchslot cell-1-1' /><td class='punchmargin' rowspan='80'><span class=\"paper_field\"></span></tr>\
		<tr class='punchcard' /><td class='punchslot cell-2-10' /><td class='punchspacer' /><td class='punchslot cell-2-9' /><td class='punchspacer' /><td class='punchslot cell-2-8' /><td class='punchspacer' /><td class='punchslot cell-2-7' /><td class='punchspacer' /><td class='punchslot cell-2-6' /><td class='punchspacer' /><td class='punchslot cell-2-5' /><td class='punchspacer' /><td class='punchslot cell-2-4' /><td class='punchspacer' /><td class='punchslot cell-2-3' /><td class='punchspacer' /><td class='punchslot cell-2-2' /><td class='punchspacer' /><td class='punchslot cell-2-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-3-10' /><td class='punchspacer' /><td class='punchslot cell-3-9' /><td class='punchspacer' /><td class='punchslot cell-3-8' /><td class='punchspacer' /><td class='punchslot cell-3-7' /><td class='punchspacer' /><td class='punchslot cell-3-6' /><td class='punchspacer' /><td class='punchslot cell-3-5' /><td class='punchspacer' /><td class='punchslot cell-3-4' /><td class='punchspacer' /><td class='punchslot cell-3-3' /><td class='punchspacer' /><td class='punchslot cell-3-2' /><td class='punchspacer' /><td class='punchslot cell-3-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-4-10' /><td class='punchspacer' /><td class='punchslot cell-4-9' /><td class='punchspacer' /><td class='punchslot cell-4-8' /><td class='punchspacer' /><td class='punchslot cell-4-7' /><td class='punchspacer' /><td class='punchslot cell-4-6' /><td class='punchspacer' /><td class='punchslot cell-4-5' /><td class='punchspacer' /><td class='punchslot cell-4-4' /><td class='punchspacer' /><td class='punchslot cell-4-3' /><td class='punchspacer' /><td class='punchslot cell-4-2' /><td class='punchspacer' /><td class='punchslot cell-4-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-5-10' /><td class='punchspacer' /><td class='punchslot cell-5-9' /><td class='punchspacer' /><td class='punchslot cell-5-8' /><td class='punchspacer' /><td class='punchslot cell-5-7' /><td class='punchspacer' /><td class='punchslot cell-5-6' /><td class='punchspacer' /><td class='punchslot cell-5-5' /><td class='punchspacer' /><td class='punchslot cell-5-4' /><td class='punchspacer' /><td class='punchslot cell-5-3' /><td class='punchspacer' /><td class='punchslot cell-5-2' /><td class='punchspacer' /><td class='punchslot cell-5-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-6-10' /><td class='punchspacer' /><td class='punchslot cell-6-9' /><td class='punchspacer' /><td class='punchslot cell-6-8' /><td class='punchspacer' /><td class='punchslot cell-6-7' /><td class='punchspacer' /><td class='punchslot cell-6-6' /><td class='punchspacer' /><td class='punchslot cell-6-5' /><td class='punchspacer' /><td class='punchslot cell-6-4' /><td class='punchspacer' /><td class='punchslot cell-6-3' /><td class='punchspacer' /><td class='punchslot cell-6-2' /><td class='punchspacer' /><td class='punchslot cell-6-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-7-10' /><td class='punchspacer' /><td class='punchslot cell-7-9' /><td class='punchspacer' /><td class='punchslot cell-7-8' /><td class='punchspacer' /><td class='punchslot cell-7-7' /><td class='punchspacer' /><td class='punchslot cell-7-6' /><td class='punchspacer' /><td class='punchslot cell-7-5' /><td class='punchspacer' /><td class='punchslot cell-7-4' /><td class='punchspacer' /><td class='punchslot cell-7-3' /><td class='punchspacer' /><td class='punchslot cell-7-2' /><td class='punchspacer' /><td class='punchslot cell-7-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-8-10' /><td class='punchspacer' /><td class='punchslot cell-8-9' /><td class='punchspacer' /><td class='punchslot cell-8-8' /><td class='punchspacer' /><td class='punchslot cell-8-7' /><td class='punchspacer' /><td class='punchslot cell-8-6' /><td class='punchspacer' /><td class='punchslot cell-8-5' /><td class='punchspacer' /><td class='punchslot cell-8-4' /><td class='punchspacer' /><td class='punchslot cell-8-3' /><td class='punchspacer' /><td class='punchslot cell-8-2' /><td class='punchspacer' /><td class='punchslot cell-8-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-9-10' /><td class='punchspacer' /><td class='punchslot cell-9-9' /><td class='punchspacer' /><td class='punchslot cell-9-8' /><td class='punchspacer' /><td class='punchslot cell-9-7' /><td class='punchspacer' /><td class='punchslot cell-9-6' /><td class='punchspacer' /><td class='punchslot cell-9-5' /><td class='punchspacer' /><td class='punchslot cell-9-4' /><td class='punchspacer' /><td class='punchslot cell-9-3' /><td class='punchspacer' /><td class='punchslot cell-9-2' /><td class='punchspacer' /><td class='punchslot cell-9-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-10-10' /><td class='punchspacer' /><td class='punchslot cell-10-9' /><td class='punchspacer' /><td class='punchslot cell-10-8' /><td class='punchspacer' /><td class='punchslot cell-10-7' /><td class='punchspacer' /><td class='punchslot cell-10-6' /><td class='punchspacer' /><td class='punchslot cell-10-5' /><td class='punchspacer' /><td class='punchslot cell-10-4' /><td class='punchspacer' /><td class='punchslot cell-10-3' /><td class='punchspacer' /><td class='punchslot cell-10-2' /><td class='punchspacer' /><td class='punchslot cell-10-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-11-10' /><td class='punchspacer' /><td class='punchslot cell-11-9' /><td class='punchspacer' /><td class='punchslot cell-11-8' /><td class='punchspacer' /><td class='punchslot cell-11-7' /><td class='punchspacer' /><td class='punchslot cell-11-6' /><td class='punchspacer' /><td class='punchslot cell-11-5' /><td class='punchspacer' /><td class='punchslot cell-11-4' /><td class='punchspacer' /><td class='punchslot cell-11-3' /><td class='punchspacer' /><td class='punchslot cell-11-2' /><td class='punchspacer' /><td class='punchslot cell-11-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-12-10' /><td class='punchspacer' /><td class='punchslot cell-12-9' /><td class='punchspacer' /><td class='punchslot cell-12-8' /><td class='punchspacer' /><td class='punchslot cell-12-7' /><td class='punchspacer' /><td class='punchslot cell-12-6' /><td class='punchspacer' /><td class='punchslot cell-12-5' /><td class='punchspacer' /><td class='punchslot cell-12-4' /><td class='punchspacer' /><td class='punchslot cell-12-3' /><td class='punchspacer' /><td class='punchslot cell-12-2' /><td class='punchspacer' /><td class='punchslot cell-12-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-13-10' /><td class='punchspacer' /><td class='punchslot cell-13-9' /><td class='punchspacer' /><td class='punchslot cell-13-8' /><td class='punchspacer' /><td class='punchslot cell-13-7' /><td class='punchspacer' /><td class='punchslot cell-13-6' /><td class='punchspacer' /><td class='punchslot cell-13-5' /><td class='punchspacer' /><td class='punchslot cell-13-4' /><td class='punchspacer' /><td class='punchslot cell-13-3' /><td class='punchspacer' /><td class='punchslot cell-13-2' /><td class='punchspacer' /><td class='punchslot cell-13-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-14-10' /><td class='punchspacer' /><td class='punchslot cell-14-9' /><td class='punchspacer' /><td class='punchslot cell-14-8' /><td class='punchspacer' /><td class='punchslot cell-14-7' /><td class='punchspacer' /><td class='punchslot cell-14-6' /><td class='punchspacer' /><td class='punchslot cell-14-5' /><td class='punchspacer' /><td class='punchslot cell-14-4' /><td class='punchspacer' /><td class='punchslot cell-14-3' /><td class='punchspacer' /><td class='punchslot cell-14-2' /><td class='punchspacer' /><td class='punchslot cell-14-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-15-10' /><td class='punchspacer' /><td class='punchslot cell-15-9' /><td class='punchspacer' /><td class='punchslot cell-15-8' /><td class='punchspacer' /><td class='punchslot cell-15-7' /><td class='punchspacer' /><td class='punchslot cell-15-6' /><td class='punchspacer' /><td class='punchslot cell-15-5' /><td class='punchspacer' /><td class='punchslot cell-15-4' /><td class='punchspacer' /><td class='punchslot cell-15-3' /><td class='punchspacer' /><td class='punchslot cell-15-2' /><td class='punchspacer' /><td class='punchslot cell-15-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-16-10' /><td class='punchspacer' /><td class='punchslot cell-16-9' /><td class='punchspacer' /><td class='punchslot cell-16-8' /><td class='punchspacer' /><td class='punchslot cell-16-7' /><td class='punchspacer' /><td class='punchslot cell-16-6' /><td class='punchspacer' /><td class='punchslot cell-16-5' /><td class='punchspacer' /><td class='punchslot cell-16-4' /><td class='punchspacer' /><td class='punchslot cell-16-3' /><td class='punchspacer' /><td class='punchslot cell-16-2' /><td class='punchspacer' /><td class='punchslot cell-16-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-17-10' /><td class='punchspacer' /><td class='punchslot cell-17-9' /><td class='punchspacer' /><td class='punchslot cell-17-8' /><td class='punchspacer' /><td class='punchslot cell-17-7' /><td class='punchspacer' /><td class='punchslot cell-17-6' /><td class='punchspacer' /><td class='punchslot cell-17-5' /><td class='punchspacer' /><td class='punchslot cell-17-4' /><td class='punchspacer' /><td class='punchslot cell-17-3' /><td class='punchspacer' /><td class='punchslot cell-17-2' /><td class='punchspacer' /><td class='punchslot cell-17-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-18-10' /><td class='punchspacer' /><td class='punchslot cell-18-9' /><td class='punchspacer' /><td class='punchslot cell-18-8' /><td class='punchspacer' /><td class='punchslot cell-18-7' /><td class='punchspacer' /><td class='punchslot cell-18-6' /><td class='punchspacer' /><td class='punchslot cell-18-5' /><td class='punchspacer' /><td class='punchslot cell-18-4' /><td class='punchspacer' /><td class='punchslot cell-18-3' /><td class='punchspacer' /><td class='punchslot cell-18-2' /><td class='punchspacer' /><td class='punchslot cell-18-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-19-10' /><td class='punchspacer' /><td class='punchslot cell-19-9' /><td class='punchspacer' /><td class='punchslot cell-19-8' /><td class='punchspacer' /><td class='punchslot cell-19-7' /><td class='punchspacer' /><td class='punchslot cell-19-6' /><td class='punchspacer' /><td class='punchslot cell-19-5' /><td class='punchspacer' /><td class='punchslot cell-19-4' /><td class='punchspacer' /><td class='punchslot cell-19-3' /><td class='punchspacer' /><td class='punchslot cell-19-2' /><td class='punchspacer' /><td class='punchslot cell-19-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-20-10' /><td class='punchspacer' /><td class='punchslot cell-20-9' /><td class='punchspacer' /><td class='punchslot cell-20-8' /><td class='punchspacer' /><td class='punchslot cell-20-7' /><td class='punchspacer' /><td class='punchslot cell-20-6' /><td class='punchspacer' /><td class='punchslot cell-20-5' /><td class='punchspacer' /><td class='punchslot cell-20-4' /><td class='punchspacer' /><td class='punchslot cell-20-3' /><td class='punchspacer' /><td class='punchslot cell-20-2' /><td class='punchspacer' /><td class='punchslot cell-20-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-21-10' /><td class='punchspacer' /><td class='punchslot cell-21-9' /><td class='punchspacer' /><td class='punchslot cell-21-8' /><td class='punchspacer' /><td class='punchslot cell-21-7' /><td class='punchspacer' /><td class='punchslot cell-21-6' /><td class='punchspacer' /><td class='punchslot cell-21-5' /><td class='punchspacer' /><td class='punchslot cell-21-4' /><td class='punchspacer' /><td class='punchslot cell-21-3' /><td class='punchspacer' /><td class='punchslot cell-21-2' /><td class='punchspacer' /><td class='punchslot cell-21-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-22-10' /><td class='punchspacer' /><td class='punchslot cell-22-9' /><td class='punchspacer' /><td class='punchslot cell-22-8' /><td class='punchspacer' /><td class='punchslot cell-22-7' /><td class='punchspacer' /><td class='punchslot cell-22-6' /><td class='punchspacer' /><td class='punchslot cell-22-5' /><td class='punchspacer' /><td class='punchslot cell-22-4' /><td class='punchspacer' /><td class='punchslot cell-22-3' /><td class='punchspacer' /><td class='punchslot cell-22-2' /><td class='punchspacer' /><td class='punchslot cell-22-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-23-10' /><td class='punchspacer' /><td class='punchslot cell-23-9' /><td class='punchspacer' /><td class='punchslot cell-23-8' /><td class='punchspacer' /><td class='punchslot cell-23-7' /><td class='punchspacer' /><td class='punchslot cell-23-6' /><td class='punchspacer' /><td class='punchslot cell-23-5' /><td class='punchspacer' /><td class='punchslot cell-23-4' /><td class='punchspacer' /><td class='punchslot cell-23-3' /><td class='punchspacer' /><td class='punchslot cell-23-2' /><td class='punchspacer' /><td class='punchslot cell-23-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-24-10' /><td class='punchspacer' /><td class='punchslot cell-24-9' /><td class='punchspacer' /><td class='punchslot cell-24-8' /><td class='punchspacer' /><td class='punchslot cell-24-7' /><td class='punchspacer' /><td class='punchslot cell-24-6' /><td class='punchspacer' /><td class='punchslot cell-24-5' /><td class='punchspacer' /><td class='punchslot cell-24-4' /><td class='punchspacer' /><td class='punchslot cell-24-3' /><td class='punchspacer' /><td class='punchslot cell-24-2' /><td class='punchspacer' /><td class='punchslot cell-24-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-25-10' /><td class='punchspacer' /><td class='punchslot cell-25-9' /><td class='punchspacer' /><td class='punchslot cell-25-8' /><td class='punchspacer' /><td class='punchslot cell-25-7' /><td class='punchspacer' /><td class='punchslot cell-25-6' /><td class='punchspacer' /><td class='punchslot cell-25-5' /><td class='punchspacer' /><td class='punchslot cell-25-4' /><td class='punchspacer' /><td class='punchslot cell-25-3' /><td class='punchspacer' /><td class='punchslot cell-25-2' /><td class='punchspacer' /><td class='punchslot cell-25-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-26-10' /><td class='punchspacer' /><td class='punchslot cell-26-9' /><td class='punchspacer' /><td class='punchslot cell-26-8' /><td class='punchspacer' /><td class='punchslot cell-26-7' /><td class='punchspacer' /><td class='punchslot cell-26-6' /><td class='punchspacer' /><td class='punchslot cell-26-5' /><td class='punchspacer' /><td class='punchslot cell-26-4' /><td class='punchspacer' /><td class='punchslot cell-26-3' /><td class='punchspacer' /><td class='punchslot cell-26-2' /><td class='punchspacer' /><td class='punchslot cell-26-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-27-10' /><td class='punchspacer' /><td class='punchslot cell-27-9' /><td class='punchspacer' /><td class='punchslot cell-27-8' /><td class='punchspacer' /><td class='punchslot cell-27-7' /><td class='punchspacer' /><td class='punchslot cell-27-6' /><td class='punchspacer' /><td class='punchslot cell-27-5' /><td class='punchspacer' /><td class='punchslot cell-27-4' /><td class='punchspacer' /><td class='punchslot cell-27-3' /><td class='punchspacer' /><td class='punchslot cell-27-2' /><td class='punchspacer' /><td class='punchslot cell-27-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-28-10' /><td class='punchspacer' /><td class='punchslot cell-28-9' /><td class='punchspacer' /><td class='punchslot cell-28-8' /><td class='punchspacer' /><td class='punchslot cell-28-7' /><td class='punchspacer' /><td class='punchslot cell-28-6' /><td class='punchspacer' /><td class='punchslot cell-28-5' /><td class='punchspacer' /><td class='punchslot cell-28-4' /><td class='punchspacer' /><td class='punchslot cell-28-3' /><td class='punchspacer' /><td class='punchslot cell-28-2' /><td class='punchspacer' /><td class='punchslot cell-28-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-29-10' /><td class='punchspacer' /><td class='punchslot cell-29-9' /><td class='punchspacer' /><td class='punchslot cell-29-8' /><td class='punchspacer' /><td class='punchslot cell-29-7' /><td class='punchspacer' /><td class='punchslot cell-29-6' /><td class='punchspacer' /><td class='punchslot cell-29-5' /><td class='punchspacer' /><td class='punchslot cell-29-4' /><td class='punchspacer' /><td class='punchslot cell-29-3' /><td class='punchspacer' /><td class='punchslot cell-29-2' /><td class='punchspacer' /><td class='punchslot cell-29-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-30-10' /><td class='punchspacer' /><td class='punchslot cell-30-9' /><td class='punchspacer' /><td class='punchslot cell-30-8' /><td class='punchspacer' /><td class='punchslot cell-30-7' /><td class='punchspacer' /><td class='punchslot cell-30-6' /><td class='punchspacer' /><td class='punchslot cell-30-5' /><td class='punchspacer' /><td class='punchslot cell-30-4' /><td class='punchspacer' /><td class='punchslot cell-30-3' /><td class='punchspacer' /><td class='punchslot cell-30-2' /><td class='punchspacer' /><td class='punchslot cell-30-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-31-10' /><td class='punchspacer' /><td class='punchslot cell-31-9' /><td class='punchspacer' /><td class='punchslot cell-31-8' /><td class='punchspacer' /><td class='punchslot cell-31-7' /><td class='punchspacer' /><td class='punchslot cell-31-6' /><td class='punchspacer' /><td class='punchslot cell-31-5' /><td class='punchspacer' /><td class='punchslot cell-31-4' /><td class='punchspacer' /><td class='punchslot cell-31-3' /><td class='punchspacer' /><td class='punchslot cell-31-2' /><td class='punchspacer' /><td class='punchslot cell-31-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-32-10' /><td class='punchspacer' /><td class='punchslot cell-32-9' /><td class='punchspacer' /><td class='punchslot cell-32-8' /><td class='punchspacer' /><td class='punchslot cell-32-7' /><td class='punchspacer' /><td class='punchslot cell-32-6' /><td class='punchspacer' /><td class='punchslot cell-32-5' /><td class='punchspacer' /><td class='punchslot cell-32-4' /><td class='punchspacer' /><td class='punchslot cell-32-3' /><td class='punchspacer' /><td class='punchslot cell-32-2' /><td class='punchspacer' /><td class='punchslot cell-32-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-33-10' /><td class='punchspacer' /><td class='punchslot cell-33-9' /><td class='punchspacer' /><td class='punchslot cell-33-8' /><td class='punchspacer' /><td class='punchslot cell-33-7' /><td class='punchspacer' /><td class='punchslot cell-33-6' /><td class='punchspacer' /><td class='punchslot cell-33-5' /><td class='punchspacer' /><td class='punchslot cell-33-4' /><td class='punchspacer' /><td class='punchslot cell-33-3' /><td class='punchspacer' /><td class='punchslot cell-33-2' /><td class='punchspacer' /><td class='punchslot cell-33-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-34-10' /><td class='punchspacer' /><td class='punchslot cell-34-9' /><td class='punchspacer' /><td class='punchslot cell-34-8' /><td class='punchspacer' /><td class='punchslot cell-34-7' /><td class='punchspacer' /><td class='punchslot cell-34-6' /><td class='punchspacer' /><td class='punchslot cell-34-5' /><td class='punchspacer' /><td class='punchslot cell-34-4' /><td class='punchspacer' /><td class='punchslot cell-34-3' /><td class='punchspacer' /><td class='punchslot cell-34-2' /><td class='punchspacer' /><td class='punchslot cell-34-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-35-10' /><td class='punchspacer' /><td class='punchslot cell-35-9' /><td class='punchspacer' /><td class='punchslot cell-35-8' /><td class='punchspacer' /><td class='punchslot cell-35-7' /><td class='punchspacer' /><td class='punchslot cell-35-6' /><td class='punchspacer' /><td class='punchslot cell-35-5' /><td class='punchspacer' /><td class='punchslot cell-35-4' /><td class='punchspacer' /><td class='punchslot cell-35-3' /><td class='punchspacer' /><td class='punchslot cell-35-2' /><td class='punchspacer' /><td class='punchslot cell-35-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-36-10' /><td class='punchspacer' /><td class='punchslot cell-36-9' /><td class='punchspacer' /><td class='punchslot cell-36-8' /><td class='punchspacer' /><td class='punchslot cell-36-7' /><td class='punchspacer' /><td class='punchslot cell-36-6' /><td class='punchspacer' /><td class='punchslot cell-36-5' /><td class='punchspacer' /><td class='punchslot cell-36-4' /><td class='punchspacer' /><td class='punchslot cell-36-3' /><td class='punchspacer' /><td class='punchslot cell-36-2' /><td class='punchspacer' /><td class='punchslot cell-36-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-37-10' /><td class='punchspacer' /><td class='punchslot cell-37-9' /><td class='punchspacer' /><td class='punchslot cell-37-8' /><td class='punchspacer' /><td class='punchslot cell-37-7' /><td class='punchspacer' /><td class='punchslot cell-37-6' /><td class='punchspacer' /><td class='punchslot cell-37-5' /><td class='punchspacer' /><td class='punchslot cell-37-4' /><td class='punchspacer' /><td class='punchslot cell-37-3' /><td class='punchspacer' /><td class='punchslot cell-37-2' /><td class='punchspacer' /><td class='punchslot cell-37-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-38-10' /><td class='punchspacer' /><td class='punchslot cell-38-9' /><td class='punchspacer' /><td class='punchslot cell-38-8' /><td class='punchspacer' /><td class='punchslot cell-38-7' /><td class='punchspacer' /><td class='punchslot cell-38-6' /><td class='punchspacer' /><td class='punchslot cell-38-5' /><td class='punchspacer' /><td class='punchslot cell-38-4' /><td class='punchspacer' /><td class='punchslot cell-38-3' /><td class='punchspacer' /><td class='punchslot cell-38-2' /><td class='punchspacer' /><td class='punchslot cell-38-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-39-10' /><td class='punchspacer' /><td class='punchslot cell-39-9' /><td class='punchspacer' /><td class='punchslot cell-39-8' /><td class='punchspacer' /><td class='punchslot cell-39-7' /><td class='punchspacer' /><td class='punchslot cell-39-6' /><td class='punchspacer' /><td class='punchslot cell-39-5' /><td class='punchspacer' /><td class='punchslot cell-39-4' /><td class='punchspacer' /><td class='punchslot cell-39-3' /><td class='punchspacer' /><td class='punchslot cell-39-2' /><td class='punchspacer' /><td class='punchslot cell-39-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-40-10' /><td class='punchspacer' /><td class='punchslot cell-40-9' /><td class='punchspacer' /><td class='punchslot cell-40-8' /><td class='punchspacer' /><td class='punchslot cell-40-7' /><td class='punchspacer' /><td class='punchslot cell-40-6' /><td class='punchspacer' /><td class='punchslot cell-40-5' /><td class='punchspacer' /><td class='punchslot cell-40-4' /><td class='punchspacer' /><td class='punchslot cell-40-3' /><td class='punchspacer' /><td class='punchslot cell-40-2' /><td class='punchspacer' /><td class='punchslot cell-40-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-41-10' /><td class='punchspacer' /><td class='punchslot cell-41-9' /><td class='punchspacer' /><td class='punchslot cell-41-8' /><td class='punchspacer' /><td class='punchslot cell-41-7' /><td class='punchspacer' /><td class='punchslot cell-41-6' /><td class='punchspacer' /><td class='punchslot cell-41-5' /><td class='punchspacer' /><td class='punchslot cell-41-4' /><td class='punchspacer' /><td class='punchslot cell-41-3' /><td class='punchspacer' /><td class='punchslot cell-41-2' /><td class='punchspacer' /><td class='punchslot cell-41-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-42-10' /><td class='punchspacer' /><td class='punchslot cell-42-9' /><td class='punchspacer' /><td class='punchslot cell-42-8' /><td class='punchspacer' /><td class='punchslot cell-42-7' /><td class='punchspacer' /><td class='punchslot cell-42-6' /><td class='punchspacer' /><td class='punchslot cell-42-5' /><td class='punchspacer' /><td class='punchslot cell-42-4' /><td class='punchspacer' /><td class='punchslot cell-42-3' /><td class='punchspacer' /><td class='punchslot cell-42-2' /><td class='punchspacer' /><td class='punchslot cell-42-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-43-10' /><td class='punchspacer' /><td class='punchslot cell-43-9' /><td class='punchspacer' /><td class='punchslot cell-43-8' /><td class='punchspacer' /><td class='punchslot cell-43-7' /><td class='punchspacer' /><td class='punchslot cell-43-6' /><td class='punchspacer' /><td class='punchslot cell-43-5' /><td class='punchspacer' /><td class='punchslot cell-43-4' /><td class='punchspacer' /><td class='punchslot cell-43-3' /><td class='punchspacer' /><td class='punchslot cell-43-2' /><td class='punchspacer' /><td class='punchslot cell-43-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-44-10' /><td class='punchspacer' /><td class='punchslot cell-44-9' /><td class='punchspacer' /><td class='punchslot cell-44-8' /><td class='punchspacer' /><td class='punchslot cell-44-7' /><td class='punchspacer' /><td class='punchslot cell-44-6' /><td class='punchspacer' /><td class='punchslot cell-44-5' /><td class='punchspacer' /><td class='punchslot cell-44-4' /><td class='punchspacer' /><td class='punchslot cell-44-3' /><td class='punchspacer' /><td class='punchslot cell-44-2' /><td class='punchspacer' /><td class='punchslot cell-44-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-45-10' /><td class='punchspacer' /><td class='punchslot cell-45-9' /><td class='punchspacer' /><td class='punchslot cell-45-8' /><td class='punchspacer' /><td class='punchslot cell-45-7' /><td class='punchspacer' /><td class='punchslot cell-45-6' /><td class='punchspacer' /><td class='punchslot cell-45-5' /><td class='punchspacer' /><td class='punchslot cell-45-4' /><td class='punchspacer' /><td class='punchslot cell-45-3' /><td class='punchspacer' /><td class='punchslot cell-45-2' /><td class='punchspacer' /><td class='punchslot cell-45-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-46-10' /><td class='punchspacer' /><td class='punchslot cell-46-9' /><td class='punchspacer' /><td class='punchslot cell-46-8' /><td class='punchspacer' /><td class='punchslot cell-46-7' /><td class='punchspacer' /><td class='punchslot cell-46-6' /><td class='punchspacer' /><td class='punchslot cell-46-5' /><td class='punchspacer' /><td class='punchslot cell-46-4' /><td class='punchspacer' /><td class='punchslot cell-46-3' /><td class='punchspacer' /><td class='punchslot cell-46-2' /><td class='punchspacer' /><td class='punchslot cell-46-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-47-10' /><td class='punchspacer' /><td class='punchslot cell-47-9' /><td class='punchspacer' /><td class='punchslot cell-47-8' /><td class='punchspacer' /><td class='punchslot cell-47-7' /><td class='punchspacer' /><td class='punchslot cell-47-6' /><td class='punchspacer' /><td class='punchslot cell-47-5' /><td class='punchspacer' /><td class='punchslot cell-47-4' /><td class='punchspacer' /><td class='punchslot cell-47-3' /><td class='punchspacer' /><td class='punchslot cell-47-2' /><td class='punchspacer' /><td class='punchslot cell-47-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-48-10' /><td class='punchspacer' /><td class='punchslot cell-48-9' /><td class='punchspacer' /><td class='punchslot cell-48-8' /><td class='punchspacer' /><td class='punchslot cell-48-7' /><td class='punchspacer' /><td class='punchslot cell-48-6' /><td class='punchspacer' /><td class='punchslot cell-48-5' /><td class='punchspacer' /><td class='punchslot cell-48-4' /><td class='punchspacer' /><td class='punchslot cell-48-3' /><td class='punchspacer' /><td class='punchslot cell-48-2' /><td class='punchspacer' /><td class='punchslot cell-48-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-49-10' /><td class='punchspacer' /><td class='punchslot cell-49-9' /><td class='punchspacer' /><td class='punchslot cell-49-8' /><td class='punchspacer' /><td class='punchslot cell-49-7' /><td class='punchspacer' /><td class='punchslot cell-49-6' /><td class='punchspacer' /><td class='punchslot cell-49-5' /><td class='punchspacer' /><td class='punchslot cell-49-4' /><td class='punchspacer' /><td class='punchslot cell-49-3' /><td class='punchspacer' /><td class='punchslot cell-49-2' /><td class='punchspacer' /><td class='punchslot cell-49-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-50-10' /><td class='punchspacer' /><td class='punchslot cell-50-9' /><td class='punchspacer' /><td class='punchslot cell-50-8' /><td class='punchspacer' /><td class='punchslot cell-50-7' /><td class='punchspacer' /><td class='punchslot cell-50-6' /><td class='punchspacer' /><td class='punchslot cell-50-5' /><td class='punchspacer' /><td class='punchslot cell-50-4' /><td class='punchspacer' /><td class='punchslot cell-50-3' /><td class='punchspacer' /><td class='punchslot cell-50-2' /><td class='punchspacer' /><td class='punchslot cell-50-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-51-10' /><td class='punchspacer' /><td class='punchslot cell-51-9' /><td class='punchspacer' /><td class='punchslot cell-51-8' /><td class='punchspacer' /><td class='punchslot cell-51-7' /><td class='punchspacer' /><td class='punchslot cell-51-6' /><td class='punchspacer' /><td class='punchslot cell-51-5' /><td class='punchspacer' /><td class='punchslot cell-51-4' /><td class='punchspacer' /><td class='punchslot cell-51-3' /><td class='punchspacer' /><td class='punchslot cell-51-2' /><td class='punchspacer' /><td class='punchslot cell-51-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-52-10' /><td class='punchspacer' /><td class='punchslot cell-52-9' /><td class='punchspacer' /><td class='punchslot cell-52-8' /><td class='punchspacer' /><td class='punchslot cell-52-7' /><td class='punchspacer' /><td class='punchslot cell-52-6' /><td class='punchspacer' /><td class='punchslot cell-52-5' /><td class='punchspacer' /><td class='punchslot cell-52-4' /><td class='punchspacer' /><td class='punchslot cell-52-3' /><td class='punchspacer' /><td class='punchslot cell-52-2' /><td class='punchspacer' /><td class='punchslot cell-52-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-53-10' /><td class='punchspacer' /><td class='punchslot cell-53-9' /><td class='punchspacer' /><td class='punchslot cell-53-8' /><td class='punchspacer' /><td class='punchslot cell-53-7' /><td class='punchspacer' /><td class='punchslot cell-53-6' /><td class='punchspacer' /><td class='punchslot cell-53-5' /><td class='punchspacer' /><td class='punchslot cell-53-4' /><td class='punchspacer' /><td class='punchslot cell-53-3' /><td class='punchspacer' /><td class='punchslot cell-53-2' /><td class='punchspacer' /><td class='punchslot cell-53-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-54-10' /><td class='punchspacer' /><td class='punchslot cell-54-9' /><td class='punchspacer' /><td class='punchslot cell-54-8' /><td class='punchspacer' /><td class='punchslot cell-54-7' /><td class='punchspacer' /><td class='punchslot cell-54-6' /><td class='punchspacer' /><td class='punchslot cell-54-5' /><td class='punchspacer' /><td class='punchslot cell-54-4' /><td class='punchspacer' /><td class='punchslot cell-54-3' /><td class='punchspacer' /><td class='punchslot cell-54-2' /><td class='punchspacer' /><td class='punchslot cell-54-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-55-10' /><td class='punchspacer' /><td class='punchslot cell-55-9' /><td class='punchspacer' /><td class='punchslot cell-55-8' /><td class='punchspacer' /><td class='punchslot cell-55-7' /><td class='punchspacer' /><td class='punchslot cell-55-6' /><td class='punchspacer' /><td class='punchslot cell-55-5' /><td class='punchspacer' /><td class='punchslot cell-55-4' /><td class='punchspacer' /><td class='punchslot cell-55-3' /><td class='punchspacer' /><td class='punchslot cell-55-2' /><td class='punchspacer' /><td class='punchslot cell-55-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-56-10' /><td class='punchspacer' /><td class='punchslot cell-56-9' /><td class='punchspacer' /><td class='punchslot cell-56-8' /><td class='punchspacer' /><td class='punchslot cell-56-7' /><td class='punchspacer' /><td class='punchslot cell-56-6' /><td class='punchspacer' /><td class='punchslot cell-56-5' /><td class='punchspacer' /><td class='punchslot cell-56-4' /><td class='punchspacer' /><td class='punchslot cell-56-3' /><td class='punchspacer' /><td class='punchslot cell-56-2' /><td class='punchspacer' /><td class='punchslot cell-56-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-57-10' /><td class='punchspacer' /><td class='punchslot cell-57-9' /><td class='punchspacer' /><td class='punchslot cell-57-8' /><td class='punchspacer' /><td class='punchslot cell-57-7' /><td class='punchspacer' /><td class='punchslot cell-57-6' /><td class='punchspacer' /><td class='punchslot cell-57-5' /><td class='punchspacer' /><td class='punchslot cell-57-4' /><td class='punchspacer' /><td class='punchslot cell-57-3' /><td class='punchspacer' /><td class='punchslot cell-57-2' /><td class='punchspacer' /><td class='punchslot cell-57-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-58-10' /><td class='punchspacer' /><td class='punchslot cell-58-9' /><td class='punchspacer' /><td class='punchslot cell-58-8' /><td class='punchspacer' /><td class='punchslot cell-58-7' /><td class='punchspacer' /><td class='punchslot cell-58-6' /><td class='punchspacer' /><td class='punchslot cell-58-5' /><td class='punchspacer' /><td class='punchslot cell-58-4' /><td class='punchspacer' /><td class='punchslot cell-58-3' /><td class='punchspacer' /><td class='punchslot cell-58-2' /><td class='punchspacer' /><td class='punchslot cell-58-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-59-10' /><td class='punchspacer' /><td class='punchslot cell-59-9' /><td class='punchspacer' /><td class='punchslot cell-59-8' /><td class='punchspacer' /><td class='punchslot cell-59-7' /><td class='punchspacer' /><td class='punchslot cell-59-6' /><td class='punchspacer' /><td class='punchslot cell-59-5' /><td class='punchspacer' /><td class='punchslot cell-59-4' /><td class='punchspacer' /><td class='punchslot cell-59-3' /><td class='punchspacer' /><td class='punchslot cell-59-2' /><td class='punchspacer' /><td class='punchslot cell-59-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-60-10' /><td class='punchspacer' /><td class='punchslot cell-60-9' /><td class='punchspacer' /><td class='punchslot cell-60-8' /><td class='punchspacer' /><td class='punchslot cell-60-7' /><td class='punchspacer' /><td class='punchslot cell-60-6' /><td class='punchspacer' /><td class='punchslot cell-60-5' /><td class='punchspacer' /><td class='punchslot cell-60-4' /><td class='punchspacer' /><td class='punchslot cell-60-3' /><td class='punchspacer' /><td class='punchslot cell-60-2' /><td class='punchspacer' /><td class='punchslot cell-60-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-61-10' /><td class='punchspacer' /><td class='punchslot cell-61-9' /><td class='punchspacer' /><td class='punchslot cell-61-8' /><td class='punchspacer' /><td class='punchslot cell-61-7' /><td class='punchspacer' /><td class='punchslot cell-61-6' /><td class='punchspacer' /><td class='punchslot cell-61-5' /><td class='punchspacer' /><td class='punchslot cell-61-4' /><td class='punchspacer' /><td class='punchslot cell-61-3' /><td class='punchspacer' /><td class='punchslot cell-61-2' /><td class='punchspacer' /><td class='punchslot cell-61-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-62-10' /><td class='punchspacer' /><td class='punchslot cell-62-9' /><td class='punchspacer' /><td class='punchslot cell-62-8' /><td class='punchspacer' /><td class='punchslot cell-62-7' /><td class='punchspacer' /><td class='punchslot cell-62-6' /><td class='punchspacer' /><td class='punchslot cell-62-5' /><td class='punchspacer' /><td class='punchslot cell-62-4' /><td class='punchspacer' /><td class='punchslot cell-62-3' /><td class='punchspacer' /><td class='punchslot cell-62-2' /><td class='punchspacer' /><td class='punchslot cell-62-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-63-10' /><td class='punchspacer' /><td class='punchslot cell-63-9' /><td class='punchspacer' /><td class='punchslot cell-63-8' /><td class='punchspacer' /><td class='punchslot cell-63-7' /><td class='punchspacer' /><td class='punchslot cell-63-6' /><td class='punchspacer' /><td class='punchslot cell-63-5' /><td class='punchspacer' /><td class='punchslot cell-63-4' /><td class='punchspacer' /><td class='punchslot cell-63-3' /><td class='punchspacer' /><td class='punchslot cell-63-2' /><td class='punchspacer' /><td class='punchslot cell-63-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-64-10' /><td class='punchspacer' /><td class='punchslot cell-64-9' /><td class='punchspacer' /><td class='punchslot cell-64-8' /><td class='punchspacer' /><td class='punchslot cell-64-7' /><td class='punchspacer' /><td class='punchslot cell-64-6' /><td class='punchspacer' /><td class='punchslot cell-64-5' /><td class='punchspacer' /><td class='punchslot cell-64-4' /><td class='punchspacer' /><td class='punchslot cell-64-3' /><td class='punchspacer' /><td class='punchslot cell-64-2' /><td class='punchspacer' /><td class='punchslot cell-64-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-65-10' /><td class='punchspacer' /><td class='punchslot cell-65-9' /><td class='punchspacer' /><td class='punchslot cell-65-8' /><td class='punchspacer' /><td class='punchslot cell-65-7' /><td class='punchspacer' /><td class='punchslot cell-65-6' /><td class='punchspacer' /><td class='punchslot cell-65-5' /><td class='punchspacer' /><td class='punchslot cell-65-4' /><td class='punchspacer' /><td class='punchslot cell-65-3' /><td class='punchspacer' /><td class='punchslot cell-65-2' /><td class='punchspacer' /><td class='punchslot cell-65-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-66-10' /><td class='punchspacer' /><td class='punchslot cell-66-9' /><td class='punchspacer' /><td class='punchslot cell-66-8' /><td class='punchspacer' /><td class='punchslot cell-66-7' /><td class='punchspacer' /><td class='punchslot cell-66-6' /><td class='punchspacer' /><td class='punchslot cell-66-5' /><td class='punchspacer' /><td class='punchslot cell-66-4' /><td class='punchspacer' /><td class='punchslot cell-66-3' /><td class='punchspacer' /><td class='punchslot cell-66-2' /><td class='punchspacer' /><td class='punchslot cell-66-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-67-10' /><td class='punchspacer' /><td class='punchslot cell-67-9' /><td class='punchspacer' /><td class='punchslot cell-67-8' /><td class='punchspacer' /><td class='punchslot cell-67-7' /><td class='punchspacer' /><td class='punchslot cell-67-6' /><td class='punchspacer' /><td class='punchslot cell-67-5' /><td class='punchspacer' /><td class='punchslot cell-67-4' /><td class='punchspacer' /><td class='punchslot cell-67-3' /><td class='punchspacer' /><td class='punchslot cell-67-2' /><td class='punchspacer' /><td class='punchslot cell-67-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-68-10' /><td class='punchspacer' /><td class='punchslot cell-68-9' /><td class='punchspacer' /><td class='punchslot cell-68-8' /><td class='punchspacer' /><td class='punchslot cell-68-7' /><td class='punchspacer' /><td class='punchslot cell-68-6' /><td class='punchspacer' /><td class='punchslot cell-68-5' /><td class='punchspacer' /><td class='punchslot cell-68-4' /><td class='punchspacer' /><td class='punchslot cell-68-3' /><td class='punchspacer' /><td class='punchslot cell-68-2' /><td class='punchspacer' /><td class='punchslot cell-68-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-69-10' /><td class='punchspacer' /><td class='punchslot cell-69-9' /><td class='punchspacer' /><td class='punchslot cell-69-8' /><td class='punchspacer' /><td class='punchslot cell-69-7' /><td class='punchspacer' /><td class='punchslot cell-69-6' /><td class='punchspacer' /><td class='punchslot cell-69-5' /><td class='punchspacer' /><td class='punchslot cell-69-4' /><td class='punchspacer' /><td class='punchslot cell-69-3' /><td class='punchspacer' /><td class='punchslot cell-69-2' /><td class='punchspacer' /><td class='punchslot cell-69-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-70-10' /><td class='punchspacer' /><td class='punchslot cell-70-9' /><td class='punchspacer' /><td class='punchslot cell-70-8' /><td class='punchspacer' /><td class='punchslot cell-70-7' /><td class='punchspacer' /><td class='punchslot cell-70-6' /><td class='punchspacer' /><td class='punchslot cell-70-5' /><td class='punchspacer' /><td class='punchslot cell-70-4' /><td class='punchspacer' /><td class='punchslot cell-70-3' /><td class='punchspacer' /><td class='punchslot cell-70-2' /><td class='punchspacer' /><td class='punchslot cell-70-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-71-10' /><td class='punchspacer' /><td class='punchslot cell-71-9' /><td class='punchspacer' /><td class='punchslot cell-71-8' /><td class='punchspacer' /><td class='punchslot cell-71-7' /><td class='punchspacer' /><td class='punchslot cell-71-6' /><td class='punchspacer' /><td class='punchslot cell-71-5' /><td class='punchspacer' /><td class='punchslot cell-71-4' /><td class='punchspacer' /><td class='punchslot cell-71-3' /><td class='punchspacer' /><td class='punchslot cell-71-2' /><td class='punchspacer' /><td class='punchslot cell-71-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-72-10' /><td class='punchspacer' /><td class='punchslot cell-72-9' /><td class='punchspacer' /><td class='punchslot cell-72-8' /><td class='punchspacer' /><td class='punchslot cell-72-7' /><td class='punchspacer' /><td class='punchslot cell-72-6' /><td class='punchspacer' /><td class='punchslot cell-72-5' /><td class='punchspacer' /><td class='punchslot cell-72-4' /><td class='punchspacer' /><td class='punchslot cell-72-3' /><td class='punchspacer' /><td class='punchslot cell-72-2' /><td class='punchspacer' /><td class='punchslot cell-72-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-73-10' /><td class='punchspacer' /><td class='punchslot cell-73-9' /><td class='punchspacer' /><td class='punchslot cell-73-8' /><td class='punchspacer' /><td class='punchslot cell-73-7' /><td class='punchspacer' /><td class='punchslot cell-73-6' /><td class='punchspacer' /><td class='punchslot cell-73-5' /><td class='punchspacer' /><td class='punchslot cell-73-4' /><td class='punchspacer' /><td class='punchslot cell-73-3' /><td class='punchspacer' /><td class='punchslot cell-73-2' /><td class='punchspacer' /><td class='punchslot cell-73-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-74-10' /><td class='punchspacer' /><td class='punchslot cell-74-9' /><td class='punchspacer' /><td class='punchslot cell-74-8' /><td class='punchspacer' /><td class='punchslot cell-74-7' /><td class='punchspacer' /><td class='punchslot cell-74-6' /><td class='punchspacer' /><td class='punchslot cell-74-5' /><td class='punchspacer' /><td class='punchslot cell-74-4' /><td class='punchspacer' /><td class='punchslot cell-74-3' /><td class='punchspacer' /><td class='punchslot cell-74-2' /><td class='punchspacer' /><td class='punchslot cell-74-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-75-10' /><td class='punchspacer' /><td class='punchslot cell-75-9' /><td class='punchspacer' /><td class='punchslot cell-75-8' /><td class='punchspacer' /><td class='punchslot cell-75-7' /><td class='punchspacer' /><td class='punchslot cell-75-6' /><td class='punchspacer' /><td class='punchslot cell-75-5' /><td class='punchspacer' /><td class='punchslot cell-75-4' /><td class='punchspacer' /><td class='punchslot cell-75-3' /><td class='punchspacer' /><td class='punchslot cell-75-2' /><td class='punchspacer' /><td class='punchslot cell-75-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-76-10' /><td class='punchspacer' /><td class='punchslot cell-76-9' /><td class='punchspacer' /><td class='punchslot cell-76-8' /><td class='punchspacer' /><td class='punchslot cell-76-7' /><td class='punchspacer' /><td class='punchslot cell-76-6' /><td class='punchspacer' /><td class='punchslot cell-76-5' /><td class='punchspacer' /><td class='punchslot cell-76-4' /><td class='punchspacer' /><td class='punchslot cell-76-3' /><td class='punchspacer' /><td class='punchslot cell-76-2' /><td class='punchspacer' /><td class='punchslot cell-76-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-77-10' /><td class='punchspacer' /><td class='punchslot cell-77-9' /><td class='punchspacer' /><td class='punchslot cell-77-8' /><td class='punchspacer' /><td class='punchslot cell-77-7' /><td class='punchspacer' /><td class='punchslot cell-77-6' /><td class='punchspacer' /><td class='punchslot cell-77-5' /><td class='punchspacer' /><td class='punchslot cell-77-4' /><td class='punchspacer' /><td class='punchslot cell-77-3' /><td class='punchspacer' /><td class='punchslot cell-77-2' /><td class='punchspacer' /><td class='punchslot cell-77-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-78-10' /><td class='punchspacer' /><td class='punchslot cell-78-9' /><td class='punchspacer' /><td class='punchslot cell-78-8' /><td class='punchspacer' /><td class='punchslot cell-78-7' /><td class='punchspacer' /><td class='punchslot cell-78-6' /><td class='punchspacer' /><td class='punchslot cell-78-5' /><td class='punchspacer' /><td class='punchslot cell-78-4' /><td class='punchspacer' /><td class='punchslot cell-78-3' /><td class='punchspacer' /><td class='punchslot cell-78-2' /><td class='punchspacer' /><td class='punchslot cell-78-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-79-10' /><td class='punchspacer' /><td class='punchslot cell-79-9' /><td class='punchspacer' /><td class='punchslot cell-79-8' /><td class='punchspacer' /><td class='punchslot cell-79-7' /><td class='punchspacer' /><td class='punchslot cell-79-6' /><td class='punchspacer' /><td class='punchslot cell-79-5' /><td class='punchspacer' /><td class='punchslot cell-79-4' /><td class='punchspacer' /><td class='punchslot cell-79-3' /><td class='punchspacer' /><td class='punchslot cell-79-2' /><td class='punchspacer' /><td class='punchslot cell-79-1' /></tr>\
		<tr class='punchcard' /><td class='punchslot cell-80-10' /><td class='punchspacer' /><td class='punchslot cell-80-9' /><td class='punchspacer' /><td class='punchslot cell-80-8' /><td class='punchspacer' /><td class='punchslot cell-80-7' /><td class='punchspacer' /><td class='punchslot cell-80-6' /><td class='punchspacer' /><td class='punchslot cell-80-5' /><td class='punchspacer' /><td class='punchslot cell-80-4' /><td class='punchspacer' /><td class='punchslot cell-80-3' /><td class='punchspacer' /><td class='punchslot cell-80-2' /><td class='punchspacer' /><td class='punchslot cell-80-1' /></tr>\
		</table>\
		</div>"

	calculate_fields()
	punch_data(data)

/**
 * Sets data and updates info to actually punch the card (doesn't unpunch a card).
 *
 * Arguments:
 * * new_data - The new data to set (negative values or values larger than encoding will be ignored)
 * * encoding - How large the data value could be (16 aka hex for example will use two rows since they accomodate up to 20)
 */
/obj/item/paper/punch_card/proc/punch_data(list/new_data, encoding=10)
	if(encoding <= 0 || encoding > 800)
		CRASH("Invalid encoding passed to punch_data!")

	if(new_data)
		data = new_data.Copy()
	else
		// No data so not doing anything (nor do we unpunch)
		data = new_data
		updateinfolinks()
		return

	var/interval = ceil(encoding / 10)
	var/max_value = interval * 10
	for(var/data_index in 1 to length(data))
		var/current = data[data_index]
		if(!islist(current))
			punch_data_item(interval, max_value, current, data_index)
		else
			for(var/i in 1 to length(current))
				punch_data_item(interval, max_value, current[i], data_index)

	updateinfolinks()

/// Internal proc for punch_data()
/obj/item/paper/punch_card/proc/punch_data_item(interval, max_value, data_value, data_index)
	if(data_value <= 0 || data_value > max_value)
		return
	var/row_index = (data_index - 1) * interval + ceil(data_value / 10)
	var/col_index = ((data_value - 1) % 10) + 1 // 1 indexed byond makes the magic of modulo annoying
	var/query = "class='punchslot cell-[row_index]-[col_index]'"
	var/position = findtext(info, query)
	if(position) // There's only going to be one possible match so don't try to replace more than 1
		info = replacetext(info, query, "class='punchslot punched cell-[row_index]-[col_index]'", position, position + length(query))

/obj/item/paper/punch_card/updateinfolinks()
	info_links = info
	for(var/i=1, i<=min(fields, PAPER_MAX_FIELDS), i++)
		addtofield(i, "<font face=\"[deffont]\"><A href='byond://?src=\ref[src];write=[i]'>write</A></font>", links=TRUE)
	// No field at bottom

/obj/item/paper/punch_card/update_icon()
	return

/obj/item/paper/punch_card/clearpaper()
	return

/// Adds to first field some instructions
/obj/item/paper/punch_card/proc/add_instructions()
	if(fields)
		addtofield(1, "1. Decode current stream for rolling encryption challenge token.<BR>2. Decipher challenge token.<BR>3. Encode new challenge token with offset.")

/obj/item/paper/punch_card/instructional/Initialize(mapload, photo_list)
	. = ..()
	add_instructions()

/obj/item/paper/punch_card/hyperdyne/instructional/Initialize(mapload, photo_list)
	. = ..()
	add_instructions()

/// Sets data with random data with 1 punch per row (doesn't perform punch_data())
/obj/item/paper/punch_card/proc/prefill()
	data = list()
	for(var/i in 1 to 80)
		data += rand(0, 10)

/obj/item/paper/punch_card/prefilled/Initialize(mapload, photo_list)
	prefill()
	return ..()

/obj/item/paper/punch_card/hyperdyne/prefilled/Initialize(mapload, photo_list)
	prefill()
	return ..()

/// Resets data with random data with 1 punch per row (doesn't perform punch_data())
/obj/item/paper/punch_card/proc/randomfill()
	data = list()
	for(var/i in 1 to 80)
		var/list/current = list()
		for(var/j in 1 to 10)
			if(prob(50))
				current += j
		data += list(current)

/obj/item/paper/punch_card/randomfilled/Initialize(mapload, photo_list)
	randomfill()
	return ..()

/obj/item/paper/punch_card/hyperdyne/randomfilled/Initialize(mapload, photo_list)
	randomfill()
	return ..()


// ----- Encryption Punch Card Spawners -----

/obj/effect/spawner/punch_cards/Initialize(mapload, ...)
	. = ..()

	// Choose alternative variants based on map
	var/blank = /obj/item/paper/punch_card
	var/prefilled = /obj/item/paper/punch_card/prefilled
	var/randomfilled = /obj/item/paper/punch_card/randomfilled
	switch(SSmapping.configs[GROUND_MAP].map_name)
		if(MAP_SOROKYNE_STRATA)
			blank = /obj/item/paper/punch_card/hyperdyne
			prefilled = /obj/item/paper/punch_card/hyperdyne/prefilled
			randomfilled = /obj/item/paper/punch_card/hyperdyne/randomfilled

	// One blank
	new blank(loc)

	// And an extra thats either blank or filled
	if(prob(50)) // 50-50 for filled or not
		new blank(loc)
	else if(prob(50)) // Filled: 50-50 one value per row or just completely random
		new prefilled(loc)
	else
		new randomfilled(loc)

	return INITIALIZE_HINT_QDEL
