// Individual skill
/datum/skill
	/// Name of the skill
	var/skill_name = null
	/// used for the view UI
	var/readable_skill_name = null
	/// Level of skill in this... skill
	var/skill_level = 0
	/// the max level this skill can be, used for tgui
	var/max_skill_level = 0

/datum/skill/proc/get_skill_level()
	return skill_level

/datum/skill/proc/set_skill(new_level, mob/owner)
	skill_level = new_level

/datum/skill/proc/is_skilled(req_level, is_explicit = FALSE)
	if(is_explicit)
		return (skill_level == req_level)
	return (skill_level >= req_level)

// Lots of defines here. See #define/skills.dm

/datum/skill/cqc
	skill_name = SKILL_CQC
	readable_skill_name = "CQC"
	skill_level = SKILL_CQC_DEFAULT
	max_skill_level = SKILL_CQC_MAX

/datum/skill/melee_weapons
	skill_name = SKILL_MELEE_WEAPONS
	readable_skill_name = "melee weapons"
	skill_level = SKILL_MELEE_DEFAULT
	max_skill_level = SKILL_MELEE_MAX

/datum/skill/firearms
	skill_name = SKILL_FIREARMS
	skill_level = SKILL_FIREARMS_TRAINED
	max_skill_level = SKILL_FIREARMS_MAX

/datum/skill/spec_weapons
	skill_name = SKILL_SPEC_WEAPONS
	readable_skill_name = "specialist weapons"
	skill_level = SKILL_SPEC_DEFAULT
	max_skill_level = SKILL_SPEC_ALL

/datum/skill/endurance
	skill_name = SKILL_ENDURANCE
	skill_level = SKILL_ENDURANCE_WEAK
	max_skill_level = SKILL_ENDURANCE_MAX

/datum/skill/engineer
	skill_name = SKILL_ENGINEER
	skill_level = SKILL_ENGINEER_DEFAULT
	max_skill_level = SKILL_ENGINEER_MAX

/datum/skill/construction
	skill_name = SKILL_CONSTRUCTION
	skill_level = SKILL_CONSTRUCTION_DEFAULT
	max_skill_level = SKILL_CONSTRUCTION_MAX

/datum/skill/leadership
	skill_name = SKILL_LEADERSHIP
	skill_level = SKILL_LEAD_NOVICE
	max_skill_level = SKILL_LEAD_MAX

/datum/skill/leadership/set_skill(new_level, mob/living/owner)
	..()
	if(!owner)
		return

	if(!ishuman(owner))
		return

	// Give/remove issue order actions
	if(is_skilled(SKILL_LEAD_TRAINED))
		ADD_TRAIT(owner, TRAIT_LEADERSHIP, TRAIT_SOURCE_SKILL(skill_name))
	else
		REMOVE_TRAIT(owner, TRAIT_LEADERSHIP, TRAIT_SOURCE_SKILL(skill_name))

/datum/skill/medical
	skill_name = SKILL_MEDICAL
	skill_level = SKILL_MEDICAL_DEFAULT
	max_skill_level = SKILL_MEDICAL_MAX

/datum/skill/surgery
	skill_name = SKILL_SURGERY
	skill_level = SKILL_SURGERY_DEFAULT
	max_skill_level = SKILL_SURGERY_MAX

/datum/skill/surgery/set_skill(new_level, mob/living/owner)
	..()
	if(!owner)
		return

	if(!ishuman(owner))
		return

	// Give/remove surgery toggle action
	var/datum/action/surgery_toggle/surgery_action = locate() in owner.actions
	if(is_skilled(SKILL_SURGERY_NOVICE))
		if(!surgery_action)
			give_action(owner, /datum/action/surgery_toggle)
		else
			surgery_action.update_surgery_skill()
	else
		if(surgery_action)
			surgery_action.remove_from(owner)

/datum/skill/research
	skill_name = SKILL_RESEARCH
	skill_level = SKILL_RESEARCH_DEFAULT
	max_skill_level = SKILL_RESEARCH_MAX

/datum/skill/antag
	skill_name = SKILL_ANTAG
	readable_skill_name = "illegal technology"
	skill_level = SKILL_ANTAG_DEFAULT
	max_skill_level = SKILL_ANTAG_MAX

/datum/skill/pilot
	skill_name = SKILL_PILOT
	skill_level = SKILL_PILOT_DEFAULT
	max_skill_level = SKILL_PILOT_MAX

/datum/skill/navigations
	skill_name = SKILL_NAVIGATIONS
	skill_level = SKILL_NAVIGATIONS_DEFAULT
	max_skill_level = SKILL_NAVIGATIONS_MAX

/datum/skill/police
	skill_name = SKILL_POLICE
	skill_level = SKILL_POLICE_DEFAULT
	max_skill_level = SKILL_POLICE_MAX

/datum/skill/powerloader
	skill_name = SKILL_POWERLOADER
	skill_level = SKILL_POWERLOADER_DEFAULT
	max_skill_level = SKILL_POWERLOADER_MAX

/datum/skill/vehicles
	skill_name = SKILL_VEHICLE
	skill_level = SKILL_VEHICLE_DEFAULT
	max_skill_level = SKILL_VEHICLE_MAX

/datum/skill/jtac
	skill_name = SKILL_JTAC
	readable_skill_name = "JTAC"
	skill_level = SKILL_JTAC_NOVICE
	max_skill_level = SKILL_JTAC_MAX

/datum/skill/execution
	skill_name = SKILL_EXECUTION
	skill_level = SKILL_EXECUTION_DEFAULT
	max_skill_level = SKILL_EXECUTION_MAX

/datum/skill/intel
	skill_name = SKILL_INTEL
	skill_level = SKILL_INTEL_NOVICE
	max_skill_level = SKILL_INTEL_MAX

/datum/skill/domestic
	skill_name = SKILL_DOMESTIC
	skill_level = SKILL_DOMESTIC_NONE
	max_skill_level = SKILL_DOMESTIC_MAX

/datum/skill/fireman
	skill_name = SKILL_FIREMAN
	readable_skill_name = "fireman carrying"
	skill_level = SKILL_FIREMAN_DEFAULT
	max_skill_level = SKILL_FIREMAN_MAX

/// Skill with an extra S at the end is a collection of multiple skills. Basically a skillSET
/// This is to organize and provide a common interface to the huge heap of skills there are
/datum/skills
	/// The name of the skillset
	var/name
	// The mob that has this skillset
	var/mob/owner

	// List of skill datums.
	// Also, if this is populated when the datum is created, it will set the skill levels automagically
	var/list/skills = list()
	// Same as above, but for children of parents that just add a lil something else
	var/list/additional_skills = list()

/datum/skills/New(mob/skillset_owner)
	owner = skillset_owner

	// Setup every single skill
	for(var/skill_type in subtypesof(/datum/skill))
		var/datum/skill/S = new skill_type()

		// Fancy hack to convert a list of desired skill levels in each named skill into a skill level in the actual skill datum
		// Lets the skills list be used multipurposely for both storing skill datums and choosing skill levels for different skillsets
		var/predetermined_skill_level = additional_skills[S.skill_name] ? additional_skills[S.skill_name] : skills[S.skill_name]
		skills[S.skill_name] = S

		if(!isnull(predetermined_skill_level))
			S.set_skill(predetermined_skill_level, owner)

/datum/skills/Destroy()
	owner = null
	skills = null // Don't need to delete, /datum/skill should softdel
	SStgui.close_uis(src)
	return ..()

// Checks if the given skill is contained in this skillset at all
/datum/skills/proc/has_skill(skill)
	return isnull(skills[skill])

// Returns the skill DATUM for the given skill
/datum/skills/proc/get_skill(skill)
	if(!skills)
		return null
	return skills[skill]

// Returns the skill level for the given skill
/datum/skills/proc/get_skill_level(skill)
	var/datum/skill/S = get_skill(skill)
	if(!S)
		return -1
	if(QDELETED(S))
		return -1
	return S.get_skill_level()

// Sets the skill LEVEL for a given skill
/datum/skills/proc/set_skill(skill, new_level)
	var/datum/skill/S = skills[skill]
	if(!S)
		return
	return S.set_skill(new_level, owner)

/datum/skills/proc/increment_skill(skill, increment, cap)
	var/datum/skill/S = skills[skill]
	if(!S || skillcheck(owner, skill, cap))
		return
	return S.set_skill(min(cap,S.skill_level+increment), owner)

/datum/skills/proc/decrement_skill(skill, increment)
	var/datum/skill/S = skills[skill]
	if(!S)
		return
	return S.set_skill(max(0,S.skill_level-increment), owner)

// Checks if the skillset is AT LEAST skilled enough to pass a skillcheck for the given skill level
/datum/skills/proc/is_skilled(skill, req_level, is_explicit = FALSE)
	var/datum/skill/S = get_skill(skill)
	if(QDELETED(S))
		return FALSE
	return S.is_skilled(req_level, is_explicit)

// Adjusts the full skillset to a new type of skillset. Pass the datum type path for the desired skillset
/datum/skills/proc/set_skillset(skillset_type)
	var/datum/skills/skillset = new skillset_type()
	var/list/skill_levels = initial(skillset.skills)

	name = skillset.name
	for(var/skill in skill_levels)
		set_skill(skill, skill_levels[skill])
	qdel(skillset)

/*
---------------------
CIVILIAN
---------------------
*/

/datum/skills/civilian
	name = "Civilian"
	skills = list(
		SKILL_CQC = SKILL_CQC_DEFAULT,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_ENDURANCE = SKILL_ENDURANCE_NONE,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/civilian/manager
	name = "Weyland-Yutani Manager" // Semi-competent leader with basic knowledge in most things.
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
	)

/datum/skills/civilian/manager/director
	name = "Weyland-Yutani Director"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_EXECUTION = SKILL_EXECUTION_TRAINED,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
	)

/datum/skills/civilian/survivor
	name = "Survivor"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
	)

/datum/skills/civilian/survivor/manager
	name = "Weyland-Yutani Manager"
	skills = list(
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
	)

/datum/skills/civilian/survivor/goon
	name = "Survivor Goon"
	skills = list(
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/civilian/survivor/pmc
	name = "Survivor PMC"
	additional_skills = list(
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/civilian/survivor/doctor
	name = "Survivor Doctor"
	additional_skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/civilian/survivor/clf
	name = "Survivor CLF"
	additional_skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
	)

/datum/skills/civilian/survivor/scientist
	name = "Survivor Scientist"
	additional_skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
	)

/datum/skills/civilian/survivor/chef
	name = "Survivor Chef"
	additional_skills = list(
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
	)

/datum/skills/civilian/survivor/miner
	name = "Survivor Miner"
	additional_skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/civilian/survivor/trucker
	name = "Survivor Trucker"
	additional_skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
	)

/datum/skills/civilian/survivor/engineer
	name = "Survivor Engineer"
	additional_skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/civilian/survivor/chaplain
	name = "Survivor Chaplain"
	additional_skills = list(
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
	)

/datum/skills/civilian/survivor/marshal
	name = "Survivor Marshal"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
	)

/datum/skills/civilian/survivor/prisoner
	name = "Survivor Prisoner"
	additional_skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/civilian/survivor/gangleader
	name = "Survivor Gang Leader"
	additional_skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
	)

/*
---------------------
MILITARY SURVIVORS
---------------------
*/
//Hardcore survivors with poor equipment and skills, prove you're the best of the best.

/datum/skills/military/survivor/forecon_standard
	name = "Reconnaissance Rifleman"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_techician
	name = "Reconnaissance Support Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_marksman
	name = "Reconnaissance Designated Marksman"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SCOUT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_smartgunner
	name = "Reconnaissance Smartgunner"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_grenadier
	name = "Reconnaissance Grenadier"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_GRENADIER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_squad_leader
	name = "Reconnaissance Squad Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/*
---------------------
COMMAND STAFF
---------------------
*/

/datum/skills/general
	name = "General"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_EXECUTION = SKILL_EXECUTION_TRAINED, //can BE people
		SKILL_INTEL = SKILL_INTEL_EXPERT
	)

/datum/skills/commander
	name = "Commanding Officer"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_EXECUTION = SKILL_EXECUTION_TRAINED, //can BE people
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_NAVIGATIONS = SKILL_NAVIGATIONS_TRAINED //can change ship alt
	)

/datum/skills/XO
	name = "Executive Officer"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI, //to fix CIC apc.
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_POLICE = SKILL_POLICE_FLASH,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_NAVIGATIONS = SKILL_NAVIGATIONS_TRAINED,
	)

/datum/skills/SO
	name = "Staff Officer"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_POLICE = SKILL_POLICE_FLASH,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/datum/skills/SEA
	name = "Senior Enlisted Advisor"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
	)

/datum/skills/SEA/New(mob/skillset_owner)
	..()
	give_action(skillset_owner, /datum/action/looc_toggle)

/datum/skills/SEA/Destroy()
	remove_action(owner, /datum/action/looc_toggle)
	return ..()

/datum/skills/CMO
	name = "CMO"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_POLICE = SKILL_POLICE_FLASH,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/datum/skills/CMP
	name = "Chief MP"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/datum/skills/CE
	name = "Chief Engineer"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_POLICE = SKILL_POLICE_FLASH,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
		SKILL_NAVIGATIONS = SKILL_NAVIGATIONS_TRAINED,
	)

/datum/skills/RO
	name = "Requisition Officer"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_POLICE = SKILL_POLICE_FLASH,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/*
---------------------
MILITARY NONCOMBATANT
---------------------
*/

/datum/skills/doctor
	name = "Doctor"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/nurse
	name = "Nurse"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
	)

/datum/skills/researcher
	name = "Researcher"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/datum/skills/pilot
	name = "Pilot Officer"
	skills = list(
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/datum/skills/crew_chief
	name = "Dropship Crew Chief"
	skills = list(
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
	)

/datum/skills/MP
	name = "Military Police"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
	)

/datum/skills/MW
	name = "Military Warden"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
	)

/datum/skills/provost
	name = "Provost"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
	)

/datum/skills/OT
	name = "Ordnance Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
	)

/datum/skills/MT
	name = "Maintenance Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
	)

/datum/skills/mess_technician
	name = "Mess Technician"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT, // need to hunt food somehow
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER
	)

/datum/skills/CT
	name = "Cargo Technician"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
	)

/*
---------------------
SYNTHETIC
---------------------
*/

/datum/skills/synthetic
	name = "Synthetic"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_NAVIGATIONS = SKILL_NAVIGATIONS_TRAINED,
	)

/datum/skills/colonial_synthetic
	name = SYNTH_COLONY
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
	)

/datum/skills/working_joe
	name = SYNTH_WORKING_JOE
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
	)

/datum/skills/infiltrator_synthetic
	name = SYNTH_INFILTRATOR
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
	)

/*
------------------------------
United States Colonial Marines
------------------------------
*/

/datum/skills/pfc
	name = "Private"
	//same as default

/datum/skills/pfc/crafty
	name = "Crafty Private"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
	)

/datum/skills/combat_medic
	name = "Combat Medic"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/combat_medic/crafty
	name = "Crafty Combat Medic"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
	)

/datum/skills/combat_engineer
	name = "Combat Engineer"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/smartgunner
	name = "Squad Smartgunner"
	skills = list(
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/specialist
	name = "Squad Weapons Specialist"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED, //to use c4 in demo set.
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER
	)

/datum/skills/rto
	name = "Squad Radio Telephone Operator"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/datum/skills/SL
	name = "Squad Leader"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/datum/skills/intel
	name = "Intelligence Officer"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
	)

/*
-------------------------
COLONIAL LIBERATION FRONT
-------------------------
*/

/datum/skills/clf
	name = "CLF Soldier"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/clf/combat_engineer
	name = "CLF Engineer"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/clf/combat_medic
	name = "CLF Medic"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/clf/specialist
	name = "CLF Specialist"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED, //to use c4 in demo set.
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED
	)

/datum/skills/clf/leader
	name = "CLF Leader"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI, // to use their C4
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI
	)

/datum/skills/clf/commander
	name = "CLF Cell Commander"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_EXECUTION = SKILL_EXECUTION_TRAINED,
	)

/*
-----------
FREELANCERS
-----------
*/

//NOTE: Freelancer training is similar to the USCM's, but with additional construction skills

/datum/skills/freelancer
	name = "Freelancer Private"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
	)

/datum/skills/freelancer/combat_medic
	name = "Freelancer Medic"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/freelancer/SL
	name = "Freelancer Leader"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/*
--------------------------
UNITED PROGRESSIVE PEOPLES
--------------------------
*/

//NOTE: UPP make up for their subpar gear with extreme training.

/datum/skills/upp
	name = "UPP Private"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
	)

/datum/skills/upp/combat_engineer
	name = "UPP Sapper"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
	)

/datum/skills/upp/combat_medic
	name = "UPP Medic"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER, //trained in medicine more than combat
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED
	)

/datum/skills/upp/specialist
	name = "UPP Specialist"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_UPP,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_MASTER,
	)

/datum/skills/upp/SL
	name = "UPP Squad Leader"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/datum/skills/upp/military_police
	name = "UPP Military Police"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
	)

/datum/skills/upp/officer
	name = "UPP Officer"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_POLICE = SKILL_POLICE_FLASH,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/datum/skills/upp/commander
	name = "UPP Command Officer"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)
/datum/skills/upp/conscript
	name = "UPP Conscript"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
	)

/*
----------------------------
Private Military Contractors
----------------------------
*/

//NOTE: Compared to the USCM, PMCs have additional firearms training, construction skills and policing skills

/datum/skills/pmc
	name = "PMC Private"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
	)

/datum/skills/pmc/medic
	name = "PMC Medic"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
	)

/datum/skills/pmc/medic/chem
	name = "PMC Medical Investigator"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
	)

/datum/skills/pmc/smartgunner
	name = "PMC Smartgunner"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/pmc/specialist
	name = "PMC Specialist"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/pmc/SL
	name = "PMC Leader"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/pmc/SL/chem
	name = "PMC Lead Investigator"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/pmc/tank_crew
	name = "Vehicle Crewman"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
	)

/datum/skills/pmc/doctor
	name = "PMC Triage Doctor"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER, //trained in medicine more than combat
		SKILL_CQC = SKILL_CQC_TRAINED
	)

/datum/skills/pmc/engineer
	name = "PMC Corporate Technician"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
	)

/datum/skills/pmc/director
	name = "PMC Site Director"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_EXECUTION = SKILL_EXECUTION_TRAINED,
	)

/*
---------------------
CONTRACTORS
---------------------
*/
/datum/skills/contractor
	name = "Contractor Standard"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
	)

/datum/skills/contractor/leader
	name = "Contractor Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MASTER,
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_JTAC = SKILL_JTAC_MASTER,
	)

/datum/skills/contractor/medic
	name = "Contractor Medic"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/contractor/engi
	name = "Contractor Engi"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MAX,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MAX,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_MAX,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MAX,
	)

/datum/skills/contractor/heavy
	name = "Contractor Machinegunner"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
	)

/*
---------------------
SPEC-OPS
---------------------
*/

/datum/skills/commando
	name = "Commando"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/commando/medic
	name = "Commando Medic"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/commando/leader
	name = "Commando Leader"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/commando/deathsquad
	name = "Deathsquad"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/commando/deathsquad/leader
	name = "Deathsquad Leader"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/commando/deathsquad/officer
	name = "Deathsquad Officer"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/spy
	name = "Spy"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/ninja
	name = "Ninja"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/*
---------------------
MISCELLANEOUS
---------------------
*/

/datum/skills/mercenary
	name = "Mercenary"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
	)

/datum/skills/mercenary/elite
	name = "Elite Mercenary"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/mercenary/elite/medic
	name = "Elite Mercenary Medic"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
	)

/datum/skills/mercenary/elite/engineer
	name = "Elite Mercenary Engineer"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
	)

/datum/skills/mercenary/elite/heavy
	name = "Elite Mercenary Heavy"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
	)

/datum/skills/mercenary/elite/leader
	name = "Elite Mercenary Leader"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
	)

/datum/skills/dutchmerc
	name = "Dutch's Dozen Mercenary"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
	)

/datum/skills/dutchmedic
	name = "Dutch's Dozen Medic"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
	)

/datum/skills/tank_crew
	name = "Vehicle Crewman"
	skills = list(
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/datum/skills/gladiator
	name = "Gladiator"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
	)

/datum/skills/gladiator/champion
	name = "Gladiator Champion"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/gladiator/champion/leader
	name = "Gladiator Leader"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER, //Spartacus!
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_MASTER,
	)

/datum/skills/yautja/warrior
	name = "Yautja Warrior"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_ANTAG = SKILL_ANTAG_HUNTER,
	)

/datum/skills/dutch
	name = "Dutch"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_MAX,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/datum/skills/cultist_leader
	name = "Cultist Leader"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_MASTER,
	)

/datum/skills/souto
	name = "Souto Man"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
	)

/datum/skills/everything //max it out
	name = "Ultra"
	skills = list(
		SKILL_CQC = SKILL_CQC_MAX,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_MAX,
		SKILL_FIREARMS = SKILL_FIREARMS_MAX,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_ENGINEER = SKILL_ENGINEER_MAX,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MAX,
		SKILL_LEADERSHIP = SKILL_LEAD_MAX,
		SKILL_MEDICAL = SKILL_MEDICAL_MAX,
		SKILL_SURGERY = SKILL_SURGERY_MAX,
		SKILL_RESEARCH = SKILL_RESEARCH_MAX,
		SKILL_ANTAG = SKILL_ANTAG_MAX,
		SKILL_PILOT = SKILL_PILOT_MAX,
		SKILL_POLICE = SKILL_POLICE_MAX,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_MAX,
		SKILL_JTAC = SKILL_JTAC_MAX,
		SKILL_EXECUTION = SKILL_EXECUTION_MAX,
		SKILL_INTEL = SKILL_INTEL_MAX,
	)
