DEFINE_ENTITY(chemical_information, "chemical_information")
	var/list/properties
FIELD_STRING_SMALL(chemical_information, color)
FIELD_INT(chemical_information, explosive)
FIELD_DECIMAL(chemical_information, power)
FIELD_DECIMAL(chemical_information, falloff_modifier)
FIELD_INT(chemical_information, chemfiresupp)
FIELD_DECIMAL(chemical_information, intensitymod)
FIELD_DECIMAL(chemical_information, durationmod)
FIELD_DECIMAL(chemical_information, radiusmod)
FIELD_STRING_SMALL(chemical_information, burncolor)
FIELD_INT(chemical_information, burncolormod)
FIELD_STRING_MAX(chemical_information, properties_text)
FIELD_INT(chemical_information, spent_chemical)

/datum/entity_meta/chemical_information/map(datum/entity/chemical_information/entity, list/values)
	..()
	if(values["properties_text"])
		entity.properties = json_decode(values["properties_text"])

/datum/entity_meta/chemical_information/unmap(datum/entity/chemical_information/entity)
	. = ..()
	if(length(entity.properties))
		.["properties_text"] = json_encode(entity.properties)
