DEFINE_ENTITY(mc_timing_info, "mc_timing_info")
FIELD_BIGINT(mc_timing_info, round_id)
FIELD_INT(mc_timing_info, round_time)
FIELD_INT(mc_timing_info, client_count)
FIELD_INT(mc_timing_info, human_count)
FIELD_INT(mc_timing_info, xeno_count)
FIELD_BIGINT(mc_timing_info, total_time_taken)
