/datum/prefab_document/provost/mp/appeal_form/New() // BANDAMARINES Translate
	var/datum/asset/asset = get_asset_datum(/datum/asset/simple/paper)
	var/dat = ""

	dat += "<body>"
	dat += "<style>"
	dat += "body {"
	dat += "margin:0 auto;"
	dat += "padding:0;"
	dat += "background-image: url('[asset.get_url_mappings()["background_white.jpg"]]');"
	dat += "background-position: center;"
	dat += "background-color: #ffffff;"
	dat += "font-family: 'Courier New';"
	dat += "color: #000000;"
	dat += "}"
	dat += ""
	dat += "i {"
	dat += "color: #000000;"
	dat += "}"
	dat += ""
	dat += "p {"
	dat += "color: #000000;"
	dat += "}"
	dat += ""
	dat += "b {"
	dat += "color: #000000;"
	dat += "}"
	dat += ""
	dat += "#provost-fax-logo {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += "#provost-fax-logo img {"
	dat += "width: 200px;"
	dat += "margin-top: 5px;"
	dat += "margin-bottom: 0px;"
	dat += "opacity: 0.;"
	dat += "}"
	dat += ""
	dat += "#width-container {"
	dat += "width: 500px;"
	dat += "min-height:500px;"
	dat += "margin:0 auto;"
	dat += "margin-top: 10px;"
	dat += "margin-bottom: 10px;"
	dat += "padding-left: 20px;"
	dat += "padding-right: 20px;"
	dat += "}"
	dat += ""
	dat += ".message-header-text p {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += ".header-title {"
	dat += "font-size: 17px;"
	dat += "font-weight: 600;"
	dat += "margin-bottom: 0px;"
	dat += "color: #FF2E2E;"
	dat += "}"
	dat += ""
	dat += ".header-subtitle {"
	dat += "font-size: 15px;"
	dat += "text-transform: uppercase;"
	dat += "letter-spacing: 1.5px;"
	dat += "color: #FF2E2E;"
	dat += "margin-top: 4px;"
	dat += "}"
	dat += ""
	dat += ".message-body-text {"
	dat += "text-align: left;"
	dat += "font-size: 17px;"
	dat += "margin-bottom: 25px;"
	dat += "}"
	dat += ""
	dat += ".signature-title{"
	dat += "font-size: 14;"
	dat += "text-transform: uppercase;"
	dat += "margin-top: 2px;"
	dat += "margin-bottom: -10px;"
	dat += "}"
	dat += ""
	dat += ".message-signature-text {"
	dat += "text-align:left;"
	dat += "font-size:10px;"
	dat += "margin-bottom: 5px;"
	dat += "line-height: 1.1;"
	dat += "}"
	dat += ""
	dat += ".subheading{"
	dat += "text-align: center;"
	dat += "margin-top: -10px;"
	dat += "margin-bottom: -10px;"
	dat += "}"
	dat += ""
	dat += ".sub-subheading{"
	dat += "text-align: center;"
	dat += "margin-top: -10px;"
	dat += "margin-bottom: -10px;"
	dat += "font-size:12px;"
	dat += "}"
	dat += ""
	dat += "</style>"
	dat += ""
	dat += "<div id=\"width-container\">"
	dat += "<div id=\"provost-fax-logo\">"
	dat += "<img src='[asset.get_url_mappings()["logo_provost.png"]]' alt=\"Provost Logo\"/>"
	dat += "</div>"
	dat += ""
	dat += "<!--Header Info here-->"
	dat += "<div class=\"message-header-text\">"
	dat += "<hr style=\"margin-top:5px; margin-bottom:-15px;\">"
	dat += "<p class=\"header-title\">Апелляционная жалоба</p>"
	dat += "<p class=\"header-subtitle\">PR301a</p>"
	dat += "<hr style=\"margin-top:-15px; margin-bottom:15px;\">"
	dat += "</div> <!-- /Heasder Info -->"
	dat += ""
	dat += ""
	dat += "<div class=\"message-body-text\">"
	dat += "<p class=\"subheading\"><b style=\"color:green;\"><u>Заполняется принимающей стороной</u></b></p><br>"
	dat += "<b>Имя расследователя:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Решение по апелляции:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Заметки или комментарии:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Подпись расследователя:</b> <span class=\"paper_field\"></span><br>"
	dat += "<hr style=\"margin-top:3px; margin-bottom:3px;\">"
	dat += "<p class=\"sub-subheading\"><b><u>Решение Главного управление Военной Полиции</u></b></p><br>"
	dat += "<p style=\"margin-top:-5px; margin-bottom:-5px; font-size:12px;\">"
	dat += "Для получения решения Главного управления Военной Полиции, пожалуйста, отправьте этот документ на соответствующий факс.<br>"
	dat += "<b>Ответ получен?:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Ответ по жалобе:</b> <span class=\"paper_field\"></span><br>"
	dat += "</p>"
	dat += "<hr style=\"margin-bottom:10px;\">"
	dat += "<p class=\"subheading\"><b style=\"color:blue;\"><u>Заполняется военной полицией</u></b></p><br>"
	dat += "<b>Дата:</b> <font face=\"Times New Roman\"><i>[time2text(REALTIMEOFDAY, "Day DD Month [GLOB.game_year]")]</i></font><br>"
	dat += "<b>Кодовый номер апелляционной жалобы:</b> [generate_appeal_ref()]<br>"
	dat += "<b>Офицер, произведший арест:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Представитель военной полиции:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Показания:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Заметки или комментарии:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Подпись представителя:</b> <span class=\"paper_field\"></span><br>"
	dat += "<hr style=\"margin-top:3px; margin-bottom:3px;\">"
	dat += "<p class=\"sub-subheading\"><b><u>Форма 'PR301b' - приказ на отложенное действие (ПнОД)</u></b></p><br>"
	dat += "<p style=\"margin-top:-5px; margin-bottom:-5px; font-size:12px;\">"
	dat += "<b>ПнОД запрашивался?:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Ответ по ПнОД:</b> <span class=\"paper_field\"></span><br>"
	dat += "</p>"
	dat += "<hr style=\"margin-bottom:10px;\">"
	dat += "<p class=\"subheading\"><b style=\"color:orange;\"><u>Заполняется апеллянтом</u></b><br></p><br>"
	dat += "<b>Имя апеллянта:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Запрашиваемый расследователь:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Показания:</b><br><span class=\"paper_field\"></span><br><br><br>"
	dat += "<b>Заметки или комментарии:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Подпись апеллянта:</b> <span class=\"paper_field\"></span><br>"
	dat += "</div> <!-- /message-body-text -->"
	dat += "<hr style=\"margin-bottom:3px; margin-top:3px;\">"
	dat += "<div class=\"message-signature-text\">"
	dat += "<p class=\"signature-title\">Право на апелляцию</p>"
	dat += "<p>Каждый, кто находится в юрисдикции военного закона, имеет право обжаловать свой приговор Начальнику Военной Полиции или Командующему (далее именуемыми расследователями) на свой выбор. Запрошенный расследователь в праве переадресовать рассмотрение жалобы иной уполномоченной стороне заместо себя. Если расследователь является непосредственным участником ареста обвиняемого, то он обязан переадресовать рассмотрение жалобы иной уполномоченной стороне.</p>"
	dat += "<p>Иной уполномоченной стороной может являтся любой сотрудник военной полиции или специально вовлеченные в дело офицеры, не участвующие в нем напрямую. В случае отсутствия уполномоченной стороны апелляция может быть обработана запрошенным расследователем от обвиняемого, напрямую не вовлеченным в дело. В иных случаях, жалоба должна быть отправлена в Главное управление Военной Полиции.</p>"
	dat += "<p>Постановление по апелляционной жалобе является окончательным и не подлежит пересмотру без вмешательства Главного управления Военной Полиции. Расследователь в праве подтвердить вину обвиняемого, изменить категорию или тяжесть вменяемой статьи, смягчить наказание вплоть до минимального или полностью оправдать обвиняемого. Обвинения не могут быть сняты при доказанной виновности обвиняемого.</p>"
	dat += "<p>Право на подачу апелляционной жалобы недействительно во время Дельта Кода, требующих эвакуации угроз, приближения враждебных сил, нахождения на борту враждебных вторженцев, бунтов или побегов. Подача жалобы так же откладывается, если обвиняемый нуждается в медицинской помощи, находится в бессознательном состоянии или в статусе сбежавшего из под стражи. <br> Апелляционные жалобы рассматриваются по принципу первой подачи т.е. время ответа может быть увеличено при наличии рассматриваемых ранее поданных заявлений.</p>"
	dat += "<p>"
	dat += "Этот документ должен быть заполнен обвиняемым и представителем военной полиции до начала рассмотрения апелляции. <b>Если этот документ не будет предоставлен обвиняемому в течение 5 минут с момента запроса, все предъявленные обвинения снимаются.</b><br>"
	dat += "После заполнения данного документа расследователь обязан приступить к рассмотрению жалобы в течение дальнейших пяти минут. В случае, если это невозможно, <b>и не является результатом ситуации, при которой право на апелляцию приостановлено</b>, военная полиция может запросить форму 'PR301b' - приказ на отложенное действие (ПнОД), указав факт запроса в этом документе."
	dat += "</p>"
	dat += "<p>"
	dat += "Форма 'PR301b' - приказ на отсроченное действие (ПнОД) - позволяет военной полиции вновь преследовать обвиняемого по вменяемым статьям, от обвинения в нарушении которых он ранее был освобожден из-за невозможности соблюдения требуемых временных рамок.<br>"
	dat += "Запрос и реализация ПнОД включает в себя освобождение обвиняемого из под стражи, заполнение соответствующего раздела в форме PR301a и отправку этой формы факсом в Главное управление Военной Полиции.<br>"
	dat += "После получения ответного факса, содержащего решение Главного управления Военной Полиции, форму PR301a необходимо обновить для указания ответа. При одобрении ПнОД обвиняемому должно быть предоставлено решение Главного управления Военной Полиции до или во время задержания."
	dat += "</p>"
	dat += "</div> <!-- /message-signature-text -->"
	dat += "</div> <!-- /width-container -->"
	dat += "</body >"




	contents = dat

/datum/prefab_document/provost/mp/appeal_form/proc/generate_appeal_ref()
	return "PR_A[rand(1000, 9999)][pick(GLOB.alphabet_uppercase)][pick(GLOB.alphabet_uppercase)]"
