/datum/prefab_document/provost/mp/appeal_form/New()
	var/datum/asset/asset = get_asset_datum(/datum/asset/simple/paper)
	var/dat = ""

	dat += "<body>"
	dat += "<style>"
	dat += "body {"
	dat += "margin:0 auto;"
	dat += "padding:0;"
	dat += "background-image: url('[asset.get_url_mappings()["background_white.jpg"]]');"
	dat += "background-position: center;"
	dat += "background-color: #ffffff;"
	dat += "font-family: Monospace;"
	dat += "color: #000000;"
	dat += "}"
	dat += ""
	dat += "i {"
	dat += "color: #000000;"
	dat += "}"
	dat += ""
	dat += "p {"
	dat += "color: #000000;"
	dat += "font-family: Verdana, Geneva, Tahoma, sans-serif;"
	dat += "}"
	dat += ""
	dat += "b {"
	dat += "color: #000000;"
	dat += "}"
	dat += ""
	dat += "#provost-fax-logo {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += "#provost-fax-logo img {"
	dat += "width: 200px;"
	dat += "margin-top: 5px;"
	dat += "margin-bottom: 0px;"
	dat += "opacity: 0.;"
	dat += "}"
	dat += ""
	dat += "#width-container {"
	dat += "width: 500px;"
	dat += "min-height:500px;"
	dat += "margin:0 auto;"
	dat += "margin-top: 10px;"
	dat += "margin-bottom: 10px;"
	dat += "padding-left: 20px;"
	dat += "padding-right: 20px;"
	dat += "}"
	dat += ""
	dat += ".message-header-text p {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += ".header-title {"
	dat += "font-size: 17px;"
	dat += "font-weight: 600;"
	dat += "margin-bottom: 0px;"
	dat += "color: #FF2E2E;"
	dat += "}"
	dat += ""
	dat += ".header-subtitle {"
	dat += "font-size: 15px;"
	dat += "text-transform: uppercase;"
	dat += "letter-spacing: 1.5px;"
	dat += "color: #FF2E2E;"
	dat += "margin-top: 4px;"
	dat += "}"
	dat += ""
	dat += ".message-body-text {"
	dat += "text-align: left;"
	dat += "font-size: 17px;"
	dat += "margin-bottom: 25px;"
	dat += "}"
	dat += ""
	dat += ".signature-title{"
	dat += "font-size: 14;"
	dat += "text-transform: uppercase;"
	dat += "margin-top: 2px;"
	dat += "margin-bottom: -10px;"
	dat += "}"
	dat += ""
	dat += ".message-signature-text {"
	dat += "text-align:left;"
	dat += "font-size:10px;"
	dat += "margin-bottom: 5px;"
	dat += "line-height: 1.1;"
	dat += "}"
	dat += ""
	dat += ".subheading{"
	dat += "text-align: center;"
	dat += "margin-top: -10px;"
	dat += "margin-bottom: -10px;"
	dat += "}"
	dat += ""
	dat += ".sub-subheading{"
	dat += "text-align: center;"
	dat += "margin-top: -10px;"
	dat += "margin-bottom: -10px;"
	dat += "font-size:12px;"
	dat += "}"
	dat += ""
	dat += "</style>"
	dat += ""
	dat += "<div id=\"width-container\">"
	dat += "<div id=\"provost-fax-logo\">"
	dat += "<img src='[asset.get_url_mappings()["logo_provost.png"]]' alt=\"Provost Logo\"/>"
	dat += "</div>"
	dat += ""
	dat += "<!--Header Info here-->"
	dat += "<div class=\"message-header-text\">"
	dat += "<hr style=\"margin-top:5px; margin-bottom:-15px;\">"
	dat += "<p class=\"header-title\">Appeals Form</p>"
	dat += "<p class=\"header-subtitle\">PR301a</p>"
	dat += "<hr style=\"margin-top:-15px; margin-bottom:15px;\">"
	dat += "</div> <!-- /Heasder Info -->"
	dat += ""
	dat += ""
	dat += "<div class=\"message-body-text\">"
	dat += "<p class=\"subheading\"><b style=\"color:green;\"><u>To be completed by Handler</u></b></p><br>"
	dat += "<b>Handler Name:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Appeal Decision:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Notes or Comments:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Handler Signature:</b> <span class=\"paper_field\"></span><br>"
	dat += "<hr style=\"margin-top:3px; margin-bottom:3px;\">"
	dat += "<p class=\"sub-subheading\"><b><u>Provost Decision</u></b></p><br>"
	dat += "<p style=\"margin-top:-5px; margin-bottom:-5px; font-size:12px;\">"
	dat += "For a Provost resolution please send this document by fax to the Provost Office.<br>"
	dat += "<b>Provost Contacted?:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Provost Response:</b> <span class=\"paper_field\"></span><br>"
	dat += "</p>"
	dat += "<hr style=\"margin-bottom:10px;\">"
	dat += "<p class=\"subheading\"><b style=\"color:blue;\"><u>To be completed by Military Police</u></b></p><br>"
	dat += "<b>Date:</b> <font face=\"Times New Roman\"><i>[time2text(REALTIMEOFDAY, "Day DD Month [GLOB.game_year]")]</i></font><br>"
	dat += "<b>Appeal Reference Number:</b> [generate_appeal_ref()]<br>"
	dat += "<b>Arresting Officer:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Department Representative:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Testimonial:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Notes or Comments:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Representative Signature:</b> <span class=\"paper_field\"></span><br>"
	dat += "<hr style=\"margin-top:3px; margin-bottom:3px;\">"
	dat += "<p class=\"sub-subheading\"><b><u>PR301b Delayed Action Order</u></b></p><br>"
	dat += "<p style=\"margin-top:-5px; margin-bottom:-5px; font-size:12px;\">"
	dat += "<b>PR301b Requested?:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>PR301b Response:</b> <span class=\"paper_field\"></span><br>"
	dat += "</p>"
	dat += "<hr style=\"margin-bottom:10px;\">"
	dat += "<p class=\"subheading\"><b style=\"color:orange;\"><u>To be completed by Defendant</u></b><br></p><br>"
	dat += "<b>Defendant Name:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Requested Handler:</b> <span class=\"paper_field\"></span><br>"
	dat += "<b>Testimonial:</b><br><span class=\"paper_field\"></span><br><br><br>"
	dat += "<b>Notes or Comments:</b><br><span class=\"paper_field\"></span><br><br>"
	dat += "<b>Defendant Signature:</b> <span class=\"paper_field\"></span><br>"
	dat += "</div> <!-- /message-body-text -->"
	dat += "<hr style=\"margin-bottom:-3px; margin-top:3px;\">"
	dat += "<div class=\"message-signature-text\">"
	dat += "<p class=\"signature-title\">Right to Appeal</p>"
	dat += "<p>Anyone under the jurisdiction of Marine Law has the right to appeal their punishment to their choice of the Chief of Military Police (CMP) or the Commander, the requested handler may designate another valid party to handle it in their place. Should either be involved in the arrest of the defendant they must designate another valid party.</p>"
	dat += "<p>Valid parties are any Military Police personnel, or Commissioned Officer, who are not directly involved in the charging, arrest of, or processing of the defendant. In the event no valid party exists the appeal may be handled by the processor of the defendant so long as they are not also directly involved in the arrest, wherein the appeal should be sent to the Provost Office.</p>"
	dat += "<p>Appeal resolutions are final and cannot be altered without intervention of the Provost Office, the handler can establish a charge as valid, modify a charge to a lower charge, reduce the punishment for a charge to the minimum punishment, and remove a charge that the prisoner is found not guilty of. Charges may not be removed if the defendant is guilty.</p>"
	dat += "<p>Right to Appeal is suspended during Delta Alert, threats mandating evacuation, approach of a hostile force, unlawful/hostile boarders, riots or jailbreaks. Appeal rights are also postponed should the defendant be in need of medical treatment, unconscious or unlawfully free of custody.<br>Appeals are handled on a first call basis, should a previously requested appeal be under review the required response time is postponed.</p>"
	dat += "<p>"
	dat += "This document must be completed by the defendant and then a Military Police representative prior to the handler beginning the appeal review. <b>Should this document not be provided to the defendant within 5 minutes of request, all charges are void.</b><br>"
	dat += "Following completion of this document the handler must begin the appeal review within a further five minutes. In the event this is not possible, <b>and not a result of a situation where Right to Appeal is suspended</b>, Military Police may seek a PR301b Delayed Action Order by indicating their request on this document."
	dat += "</p>"
	dat += "<p>"
	dat += "A PR301b Delayed Action Order (DAO) allows Military Police to reprosecute a defendant for charges they are previously released from due to the inability to adhere to the required timeframes.<br>"
	dat += "Request of a DAO requires the defendant be released from detainment, the 'PR301b Requested' section on this document completed, and a PR301b form sent by fax to the Provost Office.<br>"
	dat += "Upon receipt of a response from the DOA fax this document must be updated to indicate the Provost Office's decision. Should a DAO be approved the defendant must be presented with the response from the Provost Office upon, or prior to, being detained."
	dat += "</p>"
	dat += "</div> <!-- /message-signature-text -->"
	dat += "</div> <!-- /width-container -->"
	dat += "</body >"




	contents = dat

/datum/prefab_document/provost/mp/appeal_form/proc/generate_appeal_ref()
	return "PR_A[rand(1000, 9999)][pick(GLOB.alphabet_uppercase)][pick(GLOB.alphabet_uppercase)]"
