#define CRASH_EVAC_NONE					"CRASH_EVAC_NONE"
#define CRASH_EVAC_INPROGRESS			"CRASH_EVAC_INPROGRESS"
#define CRASH_EVAC_COMPLETED			"CRASH_EVAC_COMPLETED"

#define NUKE_NONE						"NUKE_NONE"
#define NUKE_INPROGRESS					"NUKE_INPROGRESS"
#define NUKE_COMPLETED					"NUKE_COMPLETED"
