#define MODE_NO_SHIP_MAP (1<<15)

GLOBAL_LIST_INIT(ROLES_CRASH, list(JOB_CRASH_CO, JOB_CRASH_SYNTH, JOB_CRASH_CHIEF_ENGINEER, JOB_CRASH_CMO, JOB_CRASH_SQUAD_LEADER, JOB_CRASH_SQUAD_SPECIALIST, JOB_CRASH_SQUAD_SMARTGUNNER, JOB_CRASH_SQUAD_MEDIC, JOB_CRASH_SQUAD_ENGINEER, JOB_CRASH_SQUAD_MARINE))
