GLOBAL_LIST_INIT(mob_culling_masks, list(
		/mob/living/carbon/human = "culling_human",
		/mob/living/carbon/human/yautja = "culling_human",
		/mob/living/carbon/xenomorph/facehugger = "culling_facehugger",
		/mob/living/carbon/xenomorph/larva = "culling_larva",
		/mob/living/carbon/xenomorph/lesser_drone = "culling_lesser",
		/mob/living/carbon/xenomorph/drone = "culling_drone",
		/mob/living/carbon/xenomorph/sentinel = "culling_sentinel",
		/mob/living/carbon/xenomorph/lurker = "culling_lurker",
		/mob/living/carbon/xenomorph/spitter = "culling_spitter",
		/mob/living/carbon/xenomorph/defender = "culling_defender",
		/mob/living/carbon/xenomorph/runner = "culling_runner",
		/mob/living/carbon/xenomorph/carrier = "culling_carrier",
		/mob/living/carbon/xenomorph/burrower = "culling_burrower",
		/mob/living/carbon/xenomorph/hivelord = "culling_hivelord",
		/mob/living/carbon/xenomorph/warrior = "culling_warrior",
		/mob/living/carbon/xenomorph/boiler = "culling_boiler",
		/mob/living/carbon/xenomorph/despoiler = "culling_despoiler",
		/mob/living/carbon/xenomorph/praetorian = "culling_praetorian",
		/mob/living/carbon/xenomorph/ravager = "culling_ravager",
		/mob/living/carbon/xenomorph/crusher = "culling_crusher",
		/mob/living/carbon/xenomorph/queen = "culling_queen",
		//predalien
	))

var/list/water_rerouting =  list(
	"/turf/open/gm/coast" = /turf/open/gm/river,			//we use this when putting on the overlay that will cover mobs legs
	"/turf/open/gm/coast/north" = /turf/open/gm/river,		//since if we just used the textures of coasts, part of the overlay would be sand
	"/turf/open/gm/coast/east" = /turf/open/gm/river,		//this table is used to "reroute" those to the type that holds a similar texture
	"/turf/open/gm/coast/south" = /turf/open/gm/river,		//but its completely water;
	"/turf/open/gm/coast/west" = /turf/open/gm/river,		//we use  type because we need icon and icon_state, so two birds with one stone
	"/turf/open/gm/coast/south_east" = /turf/open/gm/river, // why does this exist lol, SE but none of the other ordinals
	"/turf/open/gm/coast/beachcorner" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner/north_west" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner/north_east" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner/south_east" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner/south_west" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner2" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner2/east" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner2/north_west" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner2/north_east" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner2/south_west" = /turf/open/gm/river,
	"/turf/open/gm/coast/beachcorner2/south_east" = /turf/open/gm/river,
	"/turf/open/gm/grass/grassbeach" = /turf/open/gm/river,
	"/turf/open/gm/grass/grassbeach/north" = /turf/open/gm/river,
	"/turf/open/gm/grass/grassbeach/south" = /turf/open/gm/river,
	"/turf/open/gm/grass/grassbeach/west" = /turf/open/gm/river,
	"/turf/open/gm/grass/grassbeach/east" = /turf/open/gm/river,
	"/turf/open/desert/desert_shore" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/desert_shore1" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/desert_shore1/north" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/desert_shore1/east" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/desert_shore1/west" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_corner1" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_corner1/north" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_corner1/west" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_corner2" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_corner2/north" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_corner2/east" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_corner2/west" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_edge1" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_edge1/north" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_edge1/east" = /turf/open/gm/river/desert/shallow,
	"/turf/open/desert/desert_shore/shore_edge1/west" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/southwest" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/north" = /turf/open/gm/river/desert/deep,
	"/turf/open/gm/river/desert/shallow_edge/east" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/northeast" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/southeast" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/west" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/northwest" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/covered" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/covered/north" = /turf/open/gm/river/desert/deep,
	"/turf/open/gm/river/desert/shallow_edge/covered/east" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/covered/northeast" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_edge/covered/west" = /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_corner" = /turf/open/gm/river/desert/deep,
	"/turf/open/gm/river/desert/shallow_corner/covered"= /turf/open/gm/river/desert/deep,
	"/turf/open/gm/river/desert/shallow_corner/north"= /turf/open/gm/river/desert/deep,
	"/turf/open/gm/river/desert/shallow_corner/east"= /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/river/desert/shallow_corner/west"= /turf/open/gm/river/desert/shallow,
	"/turf/open/gm/coast/dirt" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/north" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/south" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner/north_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner/north_east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner/south_east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner/south_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner2" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner2/north_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner2/north_east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner2/south_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/beachcorner2/south_east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestdir" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestdir/south" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestdir/west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestdir/east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner/north_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner/north_east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner/south_east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner/south_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner2" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner2/north_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner2/north_east" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner2/south_west" = /turf/open/gm/river/soro,
	"/turf/open/gm/coast/dirt/forestbeachcorner2/south_east" = /turf/open/gm/river/soro,
)

var/list/coastline_water_turfs = list(
	/turf/open/gm/coast,
	/turf/open/gm/coast/north,
	/turf/open/gm/coast/east,
	/turf/open/gm/coast/south,
	/turf/open/gm/coast/west,
	/turf/open/gm/coast/south_east,
	/turf/open/gm/coast/beachcorner,
	/turf/open/gm/coast/beachcorner/north_west,
	/turf/open/gm/coast/beachcorner/north_east,
	/turf/open/gm/coast/beachcorner/south_east,
	/turf/open/gm/coast/beachcorner/south_west,
	/turf/open/gm/coast/beachcorner2,
	/turf/open/gm/coast/beachcorner2/east,
	/turf/open/gm/coast/beachcorner2/north_west,
	/turf/open/gm/coast/beachcorner2/north_east,
	/turf/open/gm/coast/beachcorner2/south_west,
	/turf/open/gm/coast/beachcorner2/south_east,
	/turf/open/gm/grass/grassbeach,
	/turf/open/gm/grass/grassbeach/north,
	/turf/open/gm/grass/grassbeach/south,
	/turf/open/gm/grass/grassbeach/west,
	/turf/open/gm/grass/grassbeach/east,
	/turf/open/desert/desert_shore,
	/turf/open/desert/desert_shore/desert_shore1,
	/turf/open/desert/desert_shore/desert_shore1/north,
	/turf/open/desert/desert_shore/desert_shore1/east,
	/turf/open/desert/desert_shore/desert_shore1/west,
	/turf/open/desert/desert_shore/shore_corner1,
	/turf/open/desert/desert_shore/shore_corner1/north,
	/turf/open/desert/desert_shore/shore_corner1/west,
	/turf/open/desert/desert_shore/shore_corner2,
	/turf/open/desert/desert_shore/shore_corner2/north,
	/turf/open/desert/desert_shore/shore_corner2/east,
	/turf/open/desert/desert_shore/shore_corner2/west,
	/turf/open/desert/desert_shore/shore_edge1,
	/turf/open/desert/desert_shore/shore_edge1/north,
	/turf/open/desert/desert_shore/shore_edge1/east,
	/turf/open/desert/desert_shore/shore_edge1/west,
	/turf/open/desert/cave/cave_shore,
	/turf/open/desert/cave/cave_shore/east,
	/turf/open/desert/cave/cave_shore/northeast,
	/turf/open/desert/cave/cave_shore/southeast,
	/turf/open/gm/coast/dirt,
	/turf/open/gm/coast/dirt/north,
	/turf/open/gm/coast/dirt/south,
	/turf/open/gm/coast/dirt/west,
	/turf/open/gm/coast/dirt/east,
	/turf/open/gm/coast/dirt/beachcorner,
	/turf/open/gm/coast/dirt/beachcorner/north_west,
	/turf/open/gm/coast/dirt/beachcorner/north_east,
	/turf/open/gm/coast/dirt/beachcorner/south_east,
	/turf/open/gm/coast/dirt/beachcorner/south_west,
	/turf/open/gm/coast/dirt/beachcorner2,
	/turf/open/gm/coast/dirt/beachcorner2/north_west,
	/turf/open/gm/coast/dirt/beachcorner2/north_east,
	/turf/open/gm/coast/dirt/beachcorner2/south_west,
	/turf/open/gm/coast/dirt/beachcorner2/south_east,
	/turf/open/gm/coast/dirt/forestdir,
	/turf/open/gm/coast/dirt/forestdir/south,
	/turf/open/gm/coast/dirt/forestdir/west,
	/turf/open/gm/coast/dirt/forestdir/east,
	/turf/open/gm/coast/dirt/forestbeachcorner,
	/turf/open/gm/coast/dirt/forestbeachcorner/north_west,
	/turf/open/gm/coast/dirt/forestbeachcorner/north_east,
	/turf/open/gm/coast/dirt/forestbeachcorner/south_east,
	/turf/open/gm/coast/dirt/forestbeachcorner/south_west,
	/turf/open/gm/coast/dirt/forestbeachcorner2,
	/turf/open/gm/coast/dirt/forestbeachcorner2/north_west,
	/turf/open/gm/coast/dirt/forestbeachcorner2/north_east,
	/turf/open/gm/coast/dirt/forestbeachcorner2/south_west,
	/turf/open/gm/coast/dirt/forestbeachcorner2/south_east,
)

var/list/full_water_turfs = list(
	"/turf/open/gm/river" = TRUE,
	"/turf/open/gm/river/poison" = TRUE,
	"/turf/open/gm/river/darkred_pool" = TRUE,
	"/turf/open/gm/river/darkred" = TRUE,
	"/turf/open/gm/river/red_pool" = TRUE,
	"/turf/open/gm/river/red" = TRUE,
	"/turf/open/gm/river/pool" = TRUE,
	"/turf/open/gm/river/pool/no_overlay" = TRUE,
	"/turf/open/gm/river/shallow_ocean_shallow_ocean" = TRUE,
	"/turf/open/gm/river/ocean" = TRUE,
	"/turf/open/gm/river/ocean/deep_ocean" = TRUE,
	"/turf/open/gm/riverdeep" = TRUE,
	"/turf/open/gm/river/no_overlay" = TRUE,
	"/turf/open/gm/river/no_overlay/sewage" = TRUE,
	"/turf/open/gm/river/desert" = TRUE,
	"/turf/open/gm/river/desert/shallow" = TRUE,
	"/turf/open/gm/river/desert/deep/toxic" = TRUE,
	"/turf/open/gm/river/desert/deep/covered" = TRUE,
	"/turf/open/gm/river/desert/deep/no_slowdown" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/southwest" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/north" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/east" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/northeast" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/southeast" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/west" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/northwest" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/covered" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/covered/north" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/covered/east" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/covered/northeast" = TRUE,
	"/turf/open/gm/river/desert/shallow_edge/covered/west" = TRUE,
	"/turf/open/gm/river/desert/shallow_corner" = TRUE,
	"/turf/open/gm/river/desert/shallow_corner/covered"= TRUE,
	"/turf/open/gm/river/desert/shallow_corner/north"= TRUE,
	"/turf/open/gm/river/desert/shallow_corner/east"= TRUE,
	"/turf/open/gm/river/desert/shallow_corner/west"= TRUE,
	"/turf/open/gm/river/desert/deep" = TRUE,
)

/proc/get_water_turf_iconstuff(turf/open/gm/T, key)
	var/turf/open/found_type = water_rerouting["[T.type]"] ? water_rerouting["[T.type]"] : T.type
	var/return_icon = found_type.icon
	var/return_icon_state = found_type.icon_state
	if(ispath(found_type, /turf/open/gm/river/desert))
		var/turf/open/gm/river/desert/Tdesert = T
		if(Tdesert.toxic == 1)
			return_icon ='icons/turf/floors/desert_water_toxic.dmi'
		else if (Tdesert.toxic == 0)
			return_icon = 'icons/turf/floors/desert_water.dmi'
		else //Tdesert.toxic == -1
			return_icon = 'icons/turf/floors/desert_water_transition.dmi'
	return key == "icon" ? return_icon : return_icon_state

/proc/is_full_water(turf/open/gm/T)
	return full_water_turfs["[T.type]"]

/proc/is_water(turf/T)
	return full_water_turfs["[T.type]"] || (T.type in coastline_water_turfs)

/proc/is_coastline(turf/open/T)
	return (T.type in coastline_water_turfs)

