//RUCM CORE DEFINES INCLUDES

#include "core_defines_ru\access.dm"
#include "core_defines_ru\battlepass.dm"
#include "core_defines_ru\conflict.dm"
#include "core_defines_ru\crash.dm"
#include "core_defines_ru\job.dm"
#include "core_defines_ru\layers.dm"
#include "core_defines_ru\mobs.dm"
#include "core_defines_ru\mode.dm"
#include "core_defines_ru\particle.dm"
#include "core_defines_ru\shuttles.dm"
#include "core_defines_ru\skills.dm"
#include "core_defines_ru\subsystems.dm"
#include "core_defines_ru\vendors.dm"
#include "core_defines_ru\xeno.dm"
#include "core_defines_ru\dcs\signals\signals_datum.dm"
#include "core_defines_ru\dcs\signals\signals_global.dm"
#include "core_defines_ru\dcs\signals\atom\mob\signals_mob.dm"
#include "core_defines_ru\dcs\signals\atom\mob\living\signals_human.dm"
#include "core_defines_ru\dcs\signals\atom\mob\living\signals_xeno.dm"
