#define CHALLENGE_NONE "none"
#define CHALLENGE_XENO "xeno_challenge"
#define CHALLENGE_HUMAN "human_challenge"

#define REWARD_CATEGORY_ARMOR "armor"
#define REWARD_CATEGORY_HELMET_FIRE "helmet_fire"
#define REWARD_CATEGORY_PARTICLE "particle"
#define REWARD_CATEGORY_TOY "toy"
#define REWARD_CATEGORY_OVERLAY "overlay"
#define REWARD_CATEGORY_SHOTGUN_RESKIN "shotgun_reskin"
#define REWARD_CATEGORY_M41A_RESKIN "m41a_reskin"
