// blood_flags
#define BLOOD_BODY (1<<0)
#define BLOOD_HANDS (1<<1)
#define BLOOD_FEET (1<<2)

#define BLOOD_ALL (BLOOD_BODY|BLOOD_HANDS|BLOOD_FEET)

#define BLOOD_COLOR_HUMAN "#980002"
#define BLOOD_COLOR_HUMAN_DRY "#500000"
#define BLOOD_COLOR_SYNTHETIC "#EEEEEE"

#define BLOOD_COLOR_NEAERA "#1d2cbf"

#define BLOOD_COLOR_XENO "#bed700"
#define BLOOD_COLOR_XENO_ROYAL "#cac703"

#define BLOOD_COLOR_YAUTJA "#81d434"
#define BLOOD_COLOR_YAUTJA_DARK "#67934a"

#define BLOOD_COLOR_ZOMBIE "#210000"
