// blood_flags
#define BLOOD_BODY (1<<0)
#define BLOOD_HANDS (1<<1)
#define BLOOD_FEET (1<<2)

#define BLOOD_ALL (BLOOD_BODY|BLOOD_HANDS|BLOOD_FEET)

#define BLOOD_COLOR_HUMAN "#A10808"
#define BLOOD_COLOR_SYNTHETIC "#EEEEEE"

#define BLOOD_COLOR_NEAERA "#1d2cbf"

#define BLOOD_COLOR_XENO "#dffc00"
#define BLOOD_COLOR_XENO_ROYAL "#bbb900"

#define BLOOD_COLOR_YAUTJA "#20d450"
#define BLOOD_COLOR_YAUTJA_DARK "#5A934A"

#define BLOOD_COLOR_ZOMBIE "#333333"
