#define MELEE_FORCE_TIER_1		5
#define MELEE_FORCE_TIER_2		10
#define MELEE_FORCE_TIER_3		15
#define MELEE_FORCE_TIER_4		20
#define MELEE_FORCE_TIER_5		25
#define MELEE_FORCE_TIER_6		30
#define MELEE_FORCE_TIER_7		35
#define MELEE_FORCE_TIER_8		40
#define MELEE_FORCE_TIER_9		45
#define MELEE_FORCE_TIER_10		50
#define MELEE_FORCE_TIER_11		55

#define MELEE_FORCE_WEAK MELEE_FORCE_TIER_2
#define MELEE_FORCE_NORMAL MELEE_FORCE_TIER_5
#define MELEE_FORCE_STRONG MELEE_FORCE_TIER_7
#define MELEE_FORCE_VERY_STRONG MELEE_FORCE_TIER_9

#define FIRE_DAMAGE_PER_LEVEL 3
#define FIRE_DAMAGE_PER_LEVEL_MOB 1.5
