#define EV_FLAG_PRIORITIZE_TRUE     1
#define EV_FLAG_PRIORITIZE_FALSE    2

#define HNDLR_FLAG_SINGLE_FIRE      1
#define HNDLR_FLAG_END_ON_TRUE      2
#define HNDLR_FLAG_END_ON_RESULT    4
#define HNDLR_FLAG_END_ON_FALSE     8