#define EVACUATION_TYPE_NONE 0
#define EVACUATION_TYPE_ADDITIVE 1
#define EVACUATION_TYPE_MULTIPLICATIVE 2

#define HIJACK_ANNOUNCE "ARES: Процедуры эвакуации"
#define XENO_HIJACK_ANNOUNCE "Вы чувствуете что-то необычное..."

#define EVACUATION_STATUS_NOT_INITIATED 0
#define EVACUATION_STATUS_INITIATED 1

#define HIJACK_OBJECTIVES_NOT_STARTED 0
#define HIJACK_OBJECTIVES_STARTED 1
#define HIJACK_OBJECTIVES_COMPLETE 2
