#define DEFAULT_MOB_STATUS_FLAGS CANKNOCKDOWN|CANPUSH|STATUS_FLAGS_DEBILITATE

#define PLAYBLE_SIMPLE_SPEED_NORMAL 2.8
#define PLAYBLE_SIMPLE_SPEED_RETREAT 2.5
#define PLAYBLE_SIMPLE_SPEED_NORMAL_CLIENT -1
#define PLAYBLE_SIMPLE_SPEED_RETREAT_CLIENT -1.5
