#define PAPER_CATEGORY_USCM "USCM"
#define PAPER_CATEGORY_USCM_HC "USCM HC"

#define PAPER_CATEGORY_MP "Military Police"
#define PAPER_CATEGORY_PROVOST "Provost"

#define PAPER_CATEGORY_LIAISON "WY Liaison"
#define PAPER_CATEGORY_WEYYU_HC "Weyland Yutani"

#define PAPER_CATEGORY_UPP_HC "UPP HC"

#define PAPER_CATEGORY_CMB_HC "CMB HC"

#define PAPER_CATEGORY_CLF_HC "CLF HC"

#define PAPER_CATEGORY_TWE_HC "TWE HC"

#define PAPER_CATEGORY_PRESS_HC "PRESS HC"
