///When using plasma to construct we need it to cost more.
#define PATHOGEN_STRUCTURE_PLASMA_MULTIPLIER 10
#define PATHOGEN_STRUCTURE_CORE "blight core"
#define PATHOGEN_STRUCTURE_CLUSTER "blight cluster"
#define PATHOGEN_STRUCTURE_PYLON "blight pylon"
#define PATHOGEN_STRUCTURE_COCOON "mycelial cocoon"
#define PATHOGEN_STRUCTURE_COCOON_BIG "huge mycelial cocoon"
#define PATHOGEN_STRUCTURE_RECOVERY  "mycelial recovery node"
#define PATHOGEN_STRUCTURE_PLASMA "mycelial plasma node"
#define PATHOGEN_STRUCTURE_SPORECASTER "blight sporecaster"
#define PATHOGEN_STRUCTURE_FOGGER "mycelial fog pillar"

#define XENO_SPEED_NEOPHYTE -1.2

//Neo
#define PATHOGEN_CREATURE_BURSTER "Bloodburster"
#define PATHOGEN_CREATURE_SPRINTER "Sprinter"
#define PATHOGEN_CREATURE_POPPER "Popper"
#define PATHOGEN_CREATURE_CONDITOR "Conditor"
#define PATHOGEN_CREATURE_NEOMORPH "Neomorph"
#define PATHOGEN_CREATURE_NEOPHYTE "Neophyte"
#define PATHOGEN_CREATURE_BLIGHT "Blight"
#define PATHOGEN_CREATURE_BRUTE "Brute"
#define PATHOGEN_CREATURE_VENATOR "Venator"
#define PATHOGEN_CREATURE_HARBINGER "Harbinger"
#define PATHOGEN_CREATURE_MATRIARCH "Matriarch"
#define PATHOGEN_CREATURE_OVERMIND "Overmind"
#define PATHOGEN_CREATURE_ABER_BURSTER "Aberrant Bloodburster"
#define PATHOGEN_CREATURE_ABERRATION "Aberration"
#define PATHOGEN_CREATURE_ARCHON "Archon"

#define OVERMIND_DETECTION_RANGE 10 //How far out (in tiles) can the hivemind detect hostiles
#define OVERMIND_DETECTION_COOLDOWN 1 MINUTES

#define PATHOGEN_T1_CASTES list(PATHOGEN_CREATURE_SPRINTER, PATHOGEN_CREATURE_NEOPHYTE)
#define PATHOGEN_T2_CASTES list(PATHOGEN_CREATURE_NEOMORPH, PATHOGEN_CREATURE_BLIGHT)
#define PATHOGEN_T3_CASTES list(PATHOGEN_CREATURE_CONDITOR, PATHOGEN_CREATURE_BRUTE, PATHOGEN_CREATURE_VENATOR, PATHOGEN_CREATURE_HARBINGER)
#define ALL_PATHOGEN_CREATURES list(PATHOGEN_CREATURE_BURSTER, PATHOGEN_CREATURE_SPRINTER, PATHOGEN_CREATURE_NEOPHYTE, PATHOGEN_CREATURE_POPPER, PATHOGEN_CREATURE_NEOMORPH, PATHOGEN_CREATURE_BLIGHT, PATHOGEN_CREATURE_CONDITOR, PATHOGEN_CREATURE_BRUTE, PATHOGEN_CREATURE_VENATOR, PATHOGEN_CREATURE_HARBINGER, PATHOGEN_CREATURE_MATRIARCH, PATHOGEN_CREATURE_OVERMIND, PATHOGEN_CREATURE_ABER_BURSTER, PATHOGEN_CREATURE_ABERRATION, PATHOGEN_CREATURE_ARCHON)

#define POPPER_COCOON_DEAD -1
#define POPPER_COCOON_GROWING 0
#define POPPER_COCOON_GROWN 1
#define POPPER_COCOON_HATCHED 2

// Pathogen spore states
#define SPORES_WAITING 0
#define SPORES_DEPLOYING 1
#define SPORES_DEPLOYED 2
