#define FACTION_USCM "USCM"
#define FACTION_WEYLAND "WY"
#define FACTION_HUMAN "HUMAN"
#define FACTION_COLONY "COLONY"

#define ROF_SINGLE "SINGLE"
#define ROF_BURST "BURST"
#define ROF_FULL_AUTO "FULL-AUTO"

#define SENTRY_CATEGORY_IFF "IFF STATUS"
#define SENTRY_CATEGORY_ROF "RATE OF FIRE"
