#define SENTRY_FACTION_OWN "INTERNAL ONLY SIGNALS"
#define SENTRY_FACTION_ALLY "OTHER ALLIES SIGNALS"

#define ROF_SINGLE "SINGLE"
#define ROF_BURST "BURST"
#define ROF_FULL_AUTO "FULL-AUTO"

#define SENTRY_CATEGORY_IFF "IFF STATUS"
#define SENTRY_CATEGORY_ROF "RATE OF FIRE"
