#define SOUND_SHATTER list('sound/effects/Glassbr1.ogg','sound/effects/Glassbr2.ogg','sound/effects/Glassbr3.ogg')
#define SOUND_WINDOWSHATTER list('sound/effects/window_shatter1.ogg','sound/effects/window_shatter2.ogg','sound/effects/window_shatter3.ogg')
#define SOUND_GLASSBREAK list('sound/effects/glassbreak1.ogg','sound/effects/glassbreak2.ogg','sound/effects/glassbreak3.ogg','sound/effects/glassbreak4.ogg') //small breaks for bottles/etc.
#define SOUND_EXPLOSION list('sound/effects/explosion1.ogg','sound/effects/explosion2.ogg','sound/effects/explosion3.ogg','sound/effects/explosion4.ogg','sound/effects/explosion5.ogg')
#define SOUND_BIGBOOM list('sound/effects/bigboom1.ogg','sound/effects/bigboom2.ogg','sound/effects/bigboom3.ogg','sound/effects/bigboom4.ogg')
#define SOUND_SPARKS list('sound/effects/sparks1.ogg','sound/effects/sparks2.ogg','sound/effects/sparks3.ogg','sound/effects/sparks4.ogg')
#define SOUND_RUSTLE list('sound/effects/rustle1.ogg','sound/effects/rustle2.ogg','sound/effects/rustle3.ogg','sound/effects/rustle4.ogg','sound/effects/rustle5.ogg')
#define SOUND_TOOLBOX list('sound/effects/toolbox.ogg')
#define SOUND_PILLBOTTLE list('sound/effects/pillbottle.ogg')
#define SOUND_RIP list('sound/effects/rip1.ogg','sound/effects/rip2.ogg')
#define SOUND_LIGHTER list('sound/effects/lighter1.ogg','sound/effects/lighter2.ogg','sound/effects/lighter3.ogg')
#define SOUND_ZIPPO_OPEN list('sound/effects/zippo_open.ogg')
#define SOUND_ZIPPO_CLOSE list('sound/effects/zippo_close.ogg')
#define SOUND_BONK list('sound/machines/bonk.ogg') //somewhat quiet, increase volume
#define SOUND_CANE_STEP list('sound/items/cane_step_1.ogg', 'sound/items/cane_step_2.ogg', 'sound/items/cane_step_3.ogg', 'sound/items/cane_step_4.ogg', 'sound/items/cane_step_5.ogg', )
#define SOUND_MATCH list('sound/effects/match.ogg')
#define SOUND_THROWING list('sound/effects/throwing/swoosh1.ogg', 'sound/effects/throwing/swoosh2.ogg', 'sound/effects/throwing/swoosh3.ogg', 'sound/effects/throwing/swoosh4.ogg')
#define SOUND_PUNCH list('sound/weapons/punch1.ogg','sound/weapons/punch2.ogg','sound/weapons/punch3.ogg','sound/weapons/punch4.ogg')
#define SOUND_SWING_HIT list('sound/weapons/genhit1.ogg', 'sound/weapons/genhit2.ogg', 'sound/weapons/genhit3.ogg')
#define SOUND_CLAN_SWORD_HIT list('sound/weapons/clan_sword_hit_1.ogg', 'sound/weapons/clan_sword_hit_2.ogg')
#define SOUND_SLAM list('sound/effects/slam1.ogg','sound/effects/slam2.ogg','sound/effects/slam3.ogg', SOUND_SLAM_RARE)
#define SOUND_SLAM_RARE list('sound/effects/slam_rare_1.ogg')
#define SOUND_PAGETURN list('sound/effects/pageturn1.ogg', 'sound/effects/pageturn2.ogg','sound/effects/pageturn3.ogg')
#define SOUND_TERMINAL_BUTTON list('sound/machines/terminal_button01.ogg', 'sound/machines/terminal_button02.ogg', 'sound/machines/terminal_button03.ogg','sound/machines/terminal_button04.ogg', 'sound/machines/terminal_button05.ogg', 'sound/machines/terminal_button06.ogg', 'sound/machines/terminal_button07.ogg', 'sound/machines/terminal_button08.ogg')
#define SOUND_KEYBOARD list('sound/machines/keyboard1.ogg', 'sound/machines/keyboard2.ogg','sound/machines/keyboard3.ogg')
#define SOUND_KEYBOARD_ALT list('sound/machines/computer_typing4.ogg', 'sound/machines/computer_typing5.ogg', 'sound/machines/computer_typing6.ogg')
// this ones unused
#define SOUND_CLOTHINGRUSTLE list('sound/handling/clothingrustle1.ogg', 'sound/handling/clothingrustle2.ogg','sound/handling/clothingrustle3.ogg','sound/handling/clothingrustle4.ogg','sound/handling/clothingrustle5.ogg')
#define SOUND_ARMOREQUIP list('sound/handling/armorequip_1.ogg','sound/handling/armorequip_2.ogg')
#define SOUND_PRY list('sound/effects/pry1.ogg', 'sound/effects/pry2.ogg','sound/effects/pry3.ogg','sound/effects/pry4.ogg')
#define SOUND_METALBANG list('sound/effects/thud1.ogg','sound/effects/thud2.ogg','sound/effects/thud3.ogg')
#define SOUND_PAPER_WRITING list('sound/items/writing_noises/paper_writing_1.wav', 'sound/items/writing_noises/paper_writing_2.wav', 'sound/items/writing_noises/paper_writing_3.wav', 'sound/items/writing_noises/paper_writing_4.ogg')

// Weapons/bullets
#define SOUND_SHELL_LOAD list('sound/weapons/shell_load1.ogg','sound/weapons/shell_load2.ogg','sound/weapons/shell_load3.ogg','sound/weapons/shell_load4.ogg')
#define SOUND_BALLISTIC_HIT list('sound/bullets/bullet_impact1.ogg','sound/bullets/bullet_impact2.ogg','sound/bullets/bullet_impact1.ogg','sound/bullets/impact_flesh_1.ogg','sound/bullets/impact_flesh_2.ogg','sound/bullets/impact_flesh_3.ogg','sound/bullets/impact_flesh_4.ogg')
#define SOUND_BALLISTIC_ARMOR list('sound/bullets/bullet_armor1.ogg','sound/bullets/bullet_armor2.ogg','sound/bullets/bullet_armor3.ogg','sound/bullets/bullet_armor4.ogg')
#define SOUND_BALLISTIC_MISS list('sound/bullets/bullet_miss1.ogg','sound/bullets/bullet_miss2.ogg','sound/bullets/bullet_miss3.ogg','sound/bullets/bullet_miss4.ogg')
#define SOUND_BALLISTIC_BOUCE list('sound/bullets/bullet_ricochet1.ogg','sound/bullets/bullet_ricochet2.ogg','sound/bullets/bullet_ricochet3.ogg','sound/bullets/bullet_ricochet4.ogg','sound/bullets/bullet_ricochet5.ogg','sound/bullets/bullet_ricochet6.ogg','sound/bullets/bullet_ricochet7.ogg','sound/bullets/bullet_ricochet8.ogg')
#define SOUND_BALLISTIC_SHIELD_HIT list('sound/bullets/shield_impact_c1.ogg','sound/bullets/shield_impact_c2.ogg','sound/bullets/shield_impact_c3.ogg','sound/bullets/shield_impact_c4.ogg')
#define SOUND_SHIELD_SHATTER list('sound/bullets/shield_break_c1.ogg')
#define SOUND_ROCKET_BOUNCE list('sound/bullets/rocket_ricochet1.ogg','sound/bullets/rocket_ricochet2.ogg','sound/bullets/rocket_ricochet3.ogg')
#define SOUND_ENERGY_HIT list('sound/bullets/energy_impact1.ogg')
#define SOUND_ENERGY_MISS list('sound/bullets/energy_miss1.ogg')
#define SOUND_ENERGY_BOUNCE list('sound/bullets/energy_ricochet1.ogg')
#define SOUND_ALLOY_HIT list('sound/bullets/spear_impact1.ogg')
#define SOUND_ALLOY_ARMOR list('sound/bullets/spear_armor1.ogg')
#define SOUND_ALLOY_BOUNCE list('sound/bullets/spear_ricochet1.ogg','sound/bullets/spear_ricochet2.ogg')
#define SOUND_GUN_SILENCED list('sound/weapons/gun_silenced_shot1.ogg','sound/weapons/gun_silenced_shot2.ogg')
#define SOUND_GUN_SILENCED_ALT list('sound/weapons/gun_silenced_alt_shot1.ogg','sound/weapons/gun_silenced_alt_shot2.ogg','sound/weapons/gun_silenced_alt_shot3.ogg')
#define SOUND_GUN_PULSE list('sound/weapons/gun_m41a_1.ogg','sound/weapons/gun_m41a_2.ogg','sound/weapons/gun_m41a_3.ogg','sound/weapons/gun_m41a_4.ogg','sound/weapons/gun_m41a_5.ogg','sound/weapons/gun_m41a_6.ogg')
#define SOUND_GUN_SMARTGUN list('sound/weapons/gun_smartgun1.ogg', 'sound/weapons/gun_smartgun2.ogg', 'sound/weapons/gun_smartgun3.ogg', 'sound/weapons/gun_smartgun4.ogg')
#define SOUND_GUN_SMARTGUN_RATTLE list('sound/weapons/gun_smartgun1_rattle.ogg', 'sound/weapons/gun_smartgun2_rattle.ogg', 'sound/weapons/gun_smartgun3_rattle.ogg', 'sound/weapons/gun_smartgun4_rattle.ogg')
#define SOUND_GUN_JAM_RACK list('sound/weapons/handling/gun_jam_rack_1.ogg', 'sound/weapons/handling/gun_jam_rack_2.ogg', 'sound/weapons/handling/gun_jam_rack_3.ogg')
#define SOUND_GUNRUSTLE list('sound/effects/gunrustle1.ogg', 'sound/effects/gunrustle2.ogg','sound/effects/gunrustle3.ogg')
#define SOUND_GUNEQUIP list('sound/handling/gunequip1.ogg','sound/handling/gunequip2.ogg','sound/handling/gunequip3.ogg')
#define SOUND_SHOTGUNPUMP list('sound/weapons/shotgunpump1.ogg','sound/weapons/shotgunpump2.ogg')

//A:CM gun sounds
#define SOUND_GUN_SHOTGUN_TACTICAL list('sound/weapons/gun_shotgun_tactical_1.ogg','sound/weapons/gun_shotgun_tactical_2.ogg','sound/weapons/gun_shotgun_tactical_3.ogg','sound/weapons/gun_shotgun_tactical_4.ogg')
#define SOUND_M4A3 list('sound/weapons/gun_m4a3_1.ogg','sound/weapons/gun_m4a3_2.ogg','sound/weapons/gun_m4a3_3.ogg','sound/weapons/gun_m4a3_4.ogg','sound/weapons/gun_m4a3_5.ogg')
#define SOUND_88M4 list('sound/weapons/gun_88m4_v7.ogg')
#define SOUND_GUN_CASING_SHOTGUN list('sound/bullets/bulletcasing_shotgun_fall1.ogg')
#define SOUND_GUN_NSG23 list('sound/weapons/gun_nsg23_1.ogg','sound/weapons/gun_nsg23_2.ogg')
#define SOUND_GUN_PKD list('sound/weapons/gun_pkd_fire01.ogg','sound/weapons/gun_pkd_fire02.ogg','sound/weapons/gun_pkd_fire03.ogg')
#define SOUND_GUN_L64 list('sound/weapons/gun_l64_1.ogg','sound/weapons/gun_l64_2.ogg','sound/weapons/gun_l64_3.ogg')

// Xeno
#define SOUND_ACID_HIT list('sound/bullets/acid_impact1.ogg')
#define SOUND_ACID_STRIKE list('sound/weapons/alien_acidstrike1.ogg','sound/weapons/alien_acidstrike2.ogg')
#define SOUND_ACID_SPIT list('sound/voice/alien_spitacid.ogg','sound/voice/alien_spitacid2.ogg')
#define SOUND_ACID_SIZZLE list('sound/effects/acid_sizzle1.ogg','sound/effects/acid_sizzle2.ogg','sound/effects/acid_sizzle3.ogg','sound/effects/acid_sizzle4.ogg')
#define SOUND_ALIEN_DOORPRY list('sound/effects/alien_doorpry1.ogg','sound/effects/alien_doorpry2.ogg')
#define SOUND_ACID_BOUNCE list('sound/bullets/acid_impact1.ogg')
#define SOUND_ALIEN_CLAW_FLESH list('sound/weapons/alien_claw_flesh1.ogg','sound/weapons/alien_claw_flesh2.ogg','sound/weapons/alien_claw_flesh3.ogg','sound/weapons/alien_claw_flesh4.ogg','sound/weapons/alien_claw_flesh5.ogg','sound/weapons/alien_claw_flesh6.ogg')
#define SOUND_ALIEN_CLAW_METAL list('sound/weapons/alien_claw_metal1.ogg','sound/weapons/alien_claw_metal2.ogg','sound/weapons/alien_claw_metal3.ogg')
#define SOUND_ALIEN_BITE list('sound/weapons/alien_bite1.ogg','sound/weapons/alien_bite2.ogg')
#define SOUND_ALIEN_FOOTSTEP_LARGE list('sound/effects/alien_footstep_large1.ogg','sound/effects/alien_footstep_large2.ogg','sound/effects/alien_footstep_large3.ogg')
#define SOUND_ALIEN_FOOTSTEP_MEDIUM list('sound/effects/alien_footstep_medium1.ogg','sound/effects/alien_footstep_medium2.ogg','sound/effects/alien_footstep_medium3.ogg')
#define SOUND_ALIEN_CHARGE list('sound/effects/alien_footstep_charge1.ogg','sound/effects/alien_footstep_charge2.ogg','sound/effects/alien_footstep_charge3.ogg')
#define SOUND_ALIEN_RESIN_BUILD list('sound/effects/alien_resin_build1.ogg','sound/effects/alien_resin_build2.ogg','sound/effects/alien_resin_build3.ogg')
#define SOUND_ALIEN_RESIN_BREAK list('sound/effects/alien_resin_break1.ogg','sound/effects/alien_resin_break2.ogg','sound/effects/alien_resin_break3.ogg')
#define SOUND_ALIEN_RESIN_MOVE list('sound/effects/alien_resin_move1.ogg','sound/effects/alien_resin_move2.ogg')
#define SOUND_ALIEN_TALK list('sound/voice/alien_talk.ogg','sound/voice/alien_talk2.ogg','sound/voice/alien_talk3.ogg')
#define SOUND_LARVA_TALK list('sound/voice/larva_talk1.ogg','sound/voice/larva_talk2.ogg','sound/voice/larva_talk3.ogg','sound/voice/larva_talk4.ogg')
#define SOUND_HISS_TALK list('sound/voice/hiss2.ogg','sound/voice/hiss3.ogg','sound/voice/hiss4.ogg')
#define SOUND_ALIEN_GROWL list('sound/voice/alien_growl1.ogg','sound/voice/alien_growl2.ogg','sound/voice/alien_growl3.ogg')
#define SOUND_ALIEN_HISS list('sound/voice/alien_hiss1.ogg','sound/voice/alien_hiss2.ogg','sound/voice/alien_hiss3.ogg')
#define SOUND_ALIEN_TAIL_SWIPE list('sound/effects/alien_tail_swipe1.ogg','sound/effects/alien_tail_swipe2.ogg','sound/effects/alien_tail_swipe3.ogg')
#define SOUND_ALIEN_HELP list('sound/voice/alien_help1.ogg','sound/voice/alien_help2.ogg','sound/voice/alien_help3.ogg')
#define SOUND_ALIEN_DROOL list('sound/voice/alien_drool1.ogg','sound/voice/alien_drool2.ogg')
#define SOUND_ALIEN_ROAR list('sound/voice/alien_roar1.ogg','sound/voice/alien_roar2.ogg','sound/voice/alien_roar3.ogg','sound/voice/alien_roar4.ogg','sound/voice/alien_roar5.ogg','sound/voice/alien_roar6.ogg')
#define SOUND_ALIEN_ROAR_LARVA list('sound/voice/alien_roar_larva1.ogg','sound/voice/alien_roar_larva2.ogg')
#define SOUND_QUEEN list('sound/voice/alien_queen_command.ogg','sound/voice/alien_queen_command2.ogg','sound/voice/alien_queen_command3.ogg')

// Human
#define SOUND_MALE_SCREAM list('sound/voice/human_male_scream_1.ogg', 'sound/voice/human_male_scream_2.ogg', 'sound/voice/human_male_scream_3.ogg', 'sound/voice/human_male_scream_4.ogg', 'sound/voice/human_male_scream_6.ogg', SOUND_MALE_SCREAM_RARE)
#define SOUND_MALE_SCREAM_RARE list('sound/voice/human_male_scream_5.ogg', 'sound/voice/human_jackson_scream.ogg', 'sound/voice/human_ack_scream.ogg')
#define SOUND_MALE_PAIN list('sound/voice/human_male_pain_1.ogg','sound/voice/human_male_pain_2.ogg','sound/voice/human_male_pain_3.ogg','sound/voice/human_male_pain_4.ogg', SOUND_MALE_PAIN_RARE)
#define SOUND_MALE_PAIN_RARE list('sound/voice/tomscream.ogg', 'sound/voice/human_bobby_pain.ogg', 'sound/voice/human_tantrum_scream.ogg', 'sound/voice/human_male_pain_rare_1.ogg')
#define SOUND_MALE_FRAGOUT list('sound/voice/human_male_grenadethrow_1.ogg', 'sound/voice/human_male_grenadethrow_2.ogg', 'sound/voice/human_male_grenadethrow_3.ogg')
#define SOUND_MALE_WARCRY list('sound/voice/warcry/male_go.ogg', 'sound/voice/warcry/male_attack.ogg', 'sound/voice/warcry/male_charge.ogg', 'sound/voice/warcry/male_charge2.ogg', 'sound/voice/warcry/warcry_male_1.ogg', 'sound/voice/warcry/warcry_male_2.ogg', 'sound/voice/warcry/warcry_male_3.ogg', 'sound/voice/warcry/warcry_male_4.ogg', 'sound/voice/warcry/warcry_male_5.ogg', 'sound/voice/warcry/warcry_male_6.ogg', 'sound/voice/warcry/warcry_male_7.ogg', 'sound/voice/warcry/warcry_male_8.ogg', 'sound/voice/warcry/warcry_male_9.ogg', 'sound/voice/warcry/warcry_male_10.ogg', 'sound/voice/warcry/warcry_male_11.ogg', 'sound/voice/warcry/warcry_male_12.ogg', 'sound/voice/warcry/warcry_male_13.ogg', 'sound/voice/warcry/warcry_male_14.ogg', 'sound/voice/warcry/warcry_male_15.ogg', 'sound/voice/warcry/warcry_male_16.ogg', 'sound/voice/warcry/warcry_male_17.ogg', 'sound/voice/warcry/warcry_male_18.ogg', 'sound/voice/warcry/warcry_male_19.ogg', 'sound/voice/warcry/warcry_male_20.ogg', 'sound/voice/warcry/warcry_male_21.ogg', 'sound/voice/warcry/warcry_male_22.ogg', 'sound/voice/warcry/warcry_male_23.ogg', 'sound/voice/warcry/warcry_male_24.ogg', 'sound/voice/warcry/warcry_male_25.ogg', 'sound/voice/warcry/warcry_male_26.ogg', 'sound/voice/warcry/warcry_male_27.ogg', 'sound/voice/warcry/warcry_male_28.ogg', 'sound/voice/warcry/warcry_male_29.ogg', 'sound/voice/warcry/warcry_male_30.ogg', 'sound/voice/warcry/warcry_male_31.ogg', 'sound/voice/warcry/warcry_male_32.ogg', 'sound/voice/warcry/warcry_male_33.ogg', 'sound/voice/warcry/warcry_male_34.ogg', 'sound/voice/warcry/warcry_male_35.ogg', SOUND_MALE_WARCRY_RARE)
#define SOUND_MALE_WARCRY_RARE list('sound/voice/warcry/warcry_male_rare_1.ogg', 'sound/voice/warcry/warcry_male_rare_2.ogg', 'sound/voice/warcry/warcry_male_rare_3.ogg', 'sound/voice/warcry/warcry_male_rare_4.ogg', 'sound/voice/warcry/warcry_male_rare_5.ogg')
#define SOUND_MALE_UPP_WARCRY list('sound/voice/upp_warcry/warcry_male_1.ogg', 'sound/voice/upp_warcry/warcry_male_2.ogg')
#define SOUND_MALE_PREBURST list('sound/voice/human_male_preburst1.ogg', 'sound/voice/human_male_preburst2.ogg', 'sound/voice/human_male_preburst3.ogg', 'sound/voice/human_male_preburst4.ogg', 'sound/voice/human_male_preburst5.ogg', 'sound/voice/human_male_preburst6.ogg', 'sound/voice/human_male_preburst7.ogg', 'sound/voice/human_male_preburst8.ogg', 'sound/voice/human_male_preburst9.ogg')
#define SOUND_MALE_HUGGED list('sound/voice/human_male_facehugged1.ogg', 'sound/voice/human_male_facehugged2.ogg', 'sound/voice/human_male_facehugged3.ogg')
#define SOUND_FEMALE_SCREAM list('sound/voice/human_female_scream_1.ogg','sound/voice/human_female_scream_2.ogg','sound/voice/human_female_scream_3.ogg','sound/voice/human_female_scream_4.ogg', SOUND_FEMALE_SCREAM_RARE)
#define SOUND_FEMALE_SCREAM_RARE list('sound/voice/human_female_scream_5.ogg')
#define SOUND_FEMALE_PAIN list('sound/voice/human_female_pain_1.ogg','sound/voice/human_female_pain_2.ogg','sound/voice/human_female_pain_3.ogg','sound/voice/human_female_pain_4.ogg')
#define SOUND_FEMALE_FRAGOUT list("sound/voice/human_female_grenadethrow_1.ogg", 'sound/voice/human_female_grenadethrow_2.ogg', 'sound/voice/human_female_grenadethrow_3.ogg')
#define SOUND_FEMALE_WARCRY list('sound/voice/warcry/female_charge.ogg', 'sound/voice/warcry/female_yell1.ogg', 'sound/voice/warcry/warcry_female_1.ogg', 'sound/voice/warcry/warcry_female_2.ogg', 'sound/voice/warcry/warcry_female_3.ogg', 'sound/voice/warcry/warcry_female_4.ogg', 'sound/voice/warcry/warcry_female_5.ogg', 'sound/voice/warcry/warcry_female_6.ogg', 'sound/voice/warcry/warcry_female_7.ogg', 'sound/voice/warcry/warcry_female_8.ogg', 'sound/voice/warcry/warcry_female_9.ogg', 'sound/voice/warcry/warcry_female_10.ogg', 'sound/voice/warcry/warcry_female_11.ogg', 'sound/voice/warcry/warcry_female_12.ogg', 'sound/voice/warcry/warcry_female_13.ogg', 'sound/voice/warcry/warcry_female_14.ogg', 'sound/voice/warcry/warcry_female_15.ogg', 'sound/voice/warcry/warcry_female_16.ogg', 'sound/voice/warcry/warcry_female_17.ogg', 'sound/voice/warcry/warcry_female_18.ogg', 'sound/voice/warcry/warcry_female_19.ogg', 'sound/voice/warcry/warcry_female_20.ogg')
#define SOUND_UPP_FEMALE_WARCRY list('sound/voice/upp_warcry/warcry_female_1.ogg', 'sound/voice/upp_warcry/warcry_female_2.ogg')
#define SOUND_FEMALE_PREBURST list('sound/voice/human_female_preburst1.ogg', 'sound/voice/human_female_preburst2.ogg', 'sound/voice/human_female_preburst3.ogg', 'sound/voice/human_female_preburst4.ogg', 'sound/voice/human_female_preburst5.ogg',  'sound/voice/human_female_preburst6.ogg',  'sound/voice/human_female_preburst7.ogg')
#define SOUND_FEMALE_HUGGED list("sound/voice/human_female_facehugged1.ogg", 'sound/voice/human_female_facehugged2.ogg')
#define SOUND_RTB_HANDSET list('sound/machines/telephone/rtb_handset_1.ogg', 'sound/machines/telephone/rtb_handset_2.ogg', 'sound/machines/telephone/rtb_handset_3.ogg', 'sound/machines/telephone/rtb_handset_4.ogg', 'sound/machines/telephone/rtb_handset_5.ogg')
#define SOUND_TALK_PHONE list('sound/machines/telephone/talk_phone1.ogg', 'sound/machines/telephone/talk_phone2.ogg', 'sound/machines/telephone/talk_phone3.ogg', 'sound/machines/telephone/talk_phone4.ogg', 'sound/machines/telephone/talk_phone5.ogg', 'sound/machines/telephone/talk_phone6.ogg', 'sound/machines/telephone/talk_phone7.ogg')
#define SOUND_BONEBREAK list('sound/effects/bone_break1.ogg','sound/effects/bone_break2.ogg','sound/effects/bone_break3.ogg','sound/effects/bone_break4.ogg','sound/effects/bone_break5.ogg','sound/effects/bone_break6.ogg','sound/effects/bone_break7.ogg','sound/effects/crack1.ogg', 'sound/effects/crack2.ogg', 'sound/effects/crackandbleed.ogg')
#define SOUND_PLUSH list('sound/items/plush1.ogg', 'sound/items/plush2.ogg', 'sound/items/plush3.ogg')

// working joe
#define SOUND_WJ_DEATH list('sound/voice/joe/death_normal.ogg', 'sound/voice/joe/death_silence.ogg', SOUND_WJ_DEATH_RARE)
#define SOUND_WJ_DEATH_RARE list('sound/voice/joe/death_tomorrow.ogg', 'sound/voice/joe/death_dream.ogg')
#define SOUND_HJ_DEATH list('sound/voice/joe/death_hj_normal.ogg', 'sound/voice/joe/death_hj_silence.ogg', SOUND_HJ_DEATH_RARE)
#define SOUND_HJ_DEATH_RARE list('sound/voice/joe/death_hj_tomorrow.ogg')
#define SOUND_UPP_WJ_DEATH list('sound/voice/joe/upp_joe/smert1.ogg', 'sound/voice/joe/upp_joe/smert2.ogg', 'sound/voice/joe/upp_joe/smert3.ogg', 'sound/voice/joe/upp_joe/smert4.ogg', 'sound/voice/joe/upp_joe/smert5.ogg')
#define SOUND_DANIEL_DEATH list('sound/voice/joe/daniel/death1.ogg', 'sound/voice/joe/daniel/death2.ogg', 'sound/voice/joe/daniel/death3.ogg')

//misc mobs
#define SOUND_CAT_MEOW list('sound/voice/cat_meow_1.ogg','sound/voice/cat_meow_2.ogg','sound/voice/cat_meow_3.ogg','sound/voice/cat_meow_4.ogg','sound/voice/cat_meow_5.ogg','sound/voice/cat_meow_6.ogg','sound/voice/cat_meow_7.ogg')
#define SOUND_PRED_PAIN list('sound/voice/pred_pain1.ogg','sound/voice/pred_pain2.ogg','sound/voice/pred_pain3.ogg','sound/voice/pred_pain4.ogg','sound/voice/pred_pain5.ogg', SOUND_PRED_PAIN_RARE)
#define SOUND_PRED_PAIN_RARE list('sound/voice/pred_pain_rare1.ogg')
#define SOUND_PRED_PREBURST list('sound/voice/pred_pain_rare1.ogg')
#define SOUND_PRED_DEATH list('sound/voice/pred_death1.ogg', 'sound/voice/pred_death2.ogg')
#define SOUND_CLOWNSTEP list('sound/effects/clownstep1.ogg', 'sound/effects/clownstep2.ogg')
#define SOUND_GIANT_LIZARD_GROWL list('sound/effects/giant_lizard_growl1.ogg', 'sound/effects/giant_lizard_growl2.ogg')
#define SOUND_GIANT_LIZARD_HISS list('sound/effects/giant_lizard_hiss1.ogg', 'sound/effects/giant_lizard_hiss2.ogg')
#define SOUND_EVO_SCREECH list('sound/voice/alien_echoroar_1.ogg', 'sound/voice/alien_echoroar_2.ogg', 'sound/voice/alien_echoroar_3.ogg')
#define SOUND_WY_DROID_PAIN list('sound/voice/wy_droid/wy_droid_pain1.ogg', 'sound/voice/wy_droid/wy_droid_pain2.ogg', 'sound/voice/wy_droid/wy_droid_pain3.ogg', 'sound/voice/wy_droid/wy_droid_pain4.ogg', 'sound/voice/wy_droid/wy_droid_pain5.ogg')
#define SOUND_WY_DROID_DEATH list('sound/voice/wy_droid/wy_droid_death1.ogg', 'sound/voice/wy_droid/wy_droid_death2.ogg', 'sound/voice/wy_droid/wy_droid_death3.ogg', 'sound/voice/wy_droid/wy_droid_death4.ogg', 'sound/voice/wy_droid/wy_droid_death5.ogg', 'sound/voice/wy_droid/wy_droid_death6.ogg', 'sound/voice/wy_droid/wy_droid_death7.ogg')
#define SOUND_WY_DROID_CLOAKER_DEATH list('sound/voice/wy_droid/wy_stealth_droid_death1.ogg', 'sound/voice/wy_droid/wy_stealth_droid_death2.ogg')
