// Wateroverlay global status
#define WATEROVERLAY_STATUS_STANDBY 0
#define WATEROVERLAY_STATUS_RUNNING 1
#define WATEROVERLAY_STATUS_DONE 2

#define DEPTH_LAND 0
#define DEPTH_COAST_SHALLOW -2
#define DEPTH_COAST_INTERMEDIATE -4
#define DEPTH_SHALLOW -8
#define DEPTH_INTERMEDIATE -12
#define DEPTH_DEEP -18
