#define isassembly(O) (istype(O, /obj/item/device/assembly))
#define isigniter(O) (istype(O, /obj/item/device/assembly/igniter))
#define isinfared(O) (istype(O, /obj/item/device/assembly/infra))
#define isprox(O) (istype(O, /obj/item/device/assembly/prox_sensor))
#define issignaller(O) (istype(O, /obj/item/device/assembly/signaller))
#define istimer(O) (istype(O, /obj/item/device/assembly/timer))
#define ismousetrap(O) (istype(O,/obj/item/device/assembly/mousetrap))