/datum/admins/proc/topic_events(var/href)
	switch(href)
		if("securitylevel")
			owner.change_security_level()
		if("distress")
			admin_force_distress()
		if("selfdestruct")
			admin_force_selfdestruct()
		if("medal")
			owner.award_medal()
		if("weaponmults")
			owner.adjust_weapon_mult()
		if("pmcguns")
			owner.toggle_gun_restrictions()
		if("monkify")
			owner.turn_everyone_into_primitives()
		if("comms_blackout")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			var/answer = alert(usr, "Would you like to alert the crew?", "Alert", "Yes", "No")
			if(answer == "Yes")
				communications_blackout(0)
			else
				communications_blackout(1)
			message_admins("[key_name_admin(usr)] triggered a communications blackout.", 1)
		if("blackout")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			message_admins("[key_name_admin(usr)] broke all lights", 1)
			lightsout(0,0)
		if("whiteout")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			for(var/obj/structure/machinery/light/L in machines)
				L.fix()
			message_admins("[key_name_admin(usr)] fixed all lights", 1)
		if("power")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			log_admin("[key_name(usr)] powered all SMESs and APCs", 1)
			message_admins(SPAN_NOTICE("[key_name_admin(usr)] powered all SMESs and APCs"), 1)
			power_restore()
		if("unpower")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			log_admin("[key_name(usr)] unpowered all SMESs and APCs", 1)
			message_admins(SPAN_NOTICE("[key_name_admin(usr)] unpowered all SMESs and APCs"), 1)
			power_failure()
		if("quickpower")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			log_admin("[key_name(usr)] powered all SMESs", 1)
			message_admins(SPAN_NOTICE("[key_name_admin(usr)] powered all SMESs"), 1)
			power_restore_quick()
		if("powereverything")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			log_admin("[key_name(usr)] powered all SMESs and APCs everywhere", 1)
			message_admins(SPAN_NOTICE("[key_name_admin(usr)] powered all SMESs and APCs everywhere"), 1)
			power_restore_everything()
		if("powershipreactors")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			log_admin("[key_name(usr)] powered all ship reactors", 1)
			message_admins(SPAN_NOTICE("[key_name_admin(usr)] powered all ship reactors"), 1)
			power_restore_ship_reactors()
		if("decrease_defcon")
			if(alert(src, "Are you sure you want to do this? It will laaag.", "Confirmation", "Yes", "No") == "No")
				return
			log_admin("[key_name(usr)] decreased DEFCON level.", 1)
			message_admins(SPAN_NOTICE("[key_name_admin(usr)] decreased DEFCON level."), 1)
			defcon_controller.decrease_defcon_level()
		if("give_defcon_points")
			var/amount = input(usr, "How many points to add?") as num
			if(amount != 0) //can add negative numbers too!
				log_admin("[key_name(usr)] added [amount] DEFCON points.", 1)
				message_admins(SPAN_NOTICE("[key_name_admin(usr)] added [amount] DEFCON points."), 1)
				objectives_controller.add_admin_points(amount)