/datum/prefab_document/wey_yu/liaison/nda_long
	var/preset_recipient = "<span class=\"paper_field\"></span>"
	var/doc_code = "WY442"

/datum/prefab_document/wey_yu/liaison/nda_long/New()
	var/datum/asset/asset = get_asset_datum(/datum/asset/simple/paper)
	var/dat = ""

	dat += "<body>"
	dat += "<style>"
	dat += "body {"
	dat += "margin:0 auto;"
	dat += "padding:0;"
	dat += "background-image: url('[asset.get_url_mappings()["background_white.jpg"]]');"
	dat += "background-position: center;"
	dat += "background-color: #ffffff;"
	dat += "font-family: 'Courier New';"
	dat += "}"
	dat += ""
	dat += "#wy-fax-logo {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += "#wy-fax-logo img {"
	dat += "width: 500px;"
	dat += "margin-top: 5px;"
	dat += "margin-bottom: 0px;"
	dat += "opacity: 0.;"
	dat += "}"
	dat += ""
	dat += ".sig-image{"
	dat += "width:425px;"
	dat += "padding-top:12px;"
	dat += "padding-bottom:26px;"
	dat += "}"
	dat += ""
	dat += "#width-container {"
	dat += "width: 500px;"
	dat += "min-height:500px;"
	dat += "margin:0 auto;"
	dat += "margin-top: 10px;"
	dat += "margin-bottom: 10px;"
	dat += "padding-left: 20px;"
	dat += "padding-right: 20px;"
	dat += "}"
	dat += ""
	dat += ".message-header-text p {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += ".header-title {"
	dat += "font-size: 19px;"
	dat += "font-weight: 600;"
	dat += "margin-bottom: 0px;"
	dat += "}"
	dat += ""
	dat += ".header-subtitle {"
	dat += "font-size: 15px;"
	dat += "text-transform: uppercase;"
	dat += "letter-spacing: 1.5px;"
	dat += "margin-top: 4px;"
	dat += "}"
	dat += ""
	dat += ".message-body-text {"
	dat += "text-align: left;"
	dat += "font-size: 17px;"
	dat += "margin-bottom: 35px;"
	dat += "}"
	dat += "}"
	dat += ""
	dat += ".message-signature-text {"
	dat += "text-align:right;"
	dat += "font-size:15px;"
	dat += "margin-bottom: 20px;"
	dat += "}"
	dat += ".signature-name {"
	dat += "font-size: 20px;"
	dat += "font-weight: 800;"
	dat += "margin-bottom: 0px;"
	dat += "}"
	dat += ""
	dat += ".signature-title{"
	dat += "font-size: 14;"
	dat += "text-transform: uppercase;"
	dat += "margin-top: 2px;"
	dat += "}"
	dat += ""
	dat += ".message-signature-small{"
	dat += "font-size: 16px;"
	dat += "font-style: italic;"
	dat += "line-height: 1.4;"
	dat += "margin-top: -6px;"
	dat += "}"
	dat += ""
	dat += ".message-signature-s-small{"
	dat += "font-size: 10px;"
	dat += "font-style: italic;"
	dat += "line-height: 1.4;"
	dat += "margin-top: -20px;"
	dat += "}"
	dat += ""
	dat += ".disclaimer{"
	dat += "font-size: 8px;"
	dat += "line-height: 1.2;"
	dat += "}"
	dat += ""
	dat += "</style>"
	dat += ""
	dat += "<div id=\"width-container\">"
	dat += "<div id=\"wy-fax-logo\">"
	dat += "<img src='[asset.get_url_mappings()["logo_wy.png"]]' alt='WY Logo'/>"
	dat += "</div>"
	dat += ""
	dat += "<!--Header Info here-->"
	dat += "<div class=\"message-header-text\">"
	dat += "<p class=\"header-title\">Non Disclosure Agreement</p>"
	dat += "<p class=\"header-subtitle\">[doc_code]</p>"
	dat += "<hr style=\"margin-top:5px; margin-bottom:35px;\">"
	dat += "</div> <!-- /Heasder Info -->"
	dat += ""
	dat += ""
	dat += "<!-- Message -->"
	dat += "<div class=\"message-body-text\">"
	dat += "This Non-disclosure Agreement is made effective as of <font face=\"Times New Roman\"><i>[time2text(REALTIMEOFDAY, "Day DD Month [GLOB.game_year]")]</i></font> by and between The Company and [preset_recipient] <b>(the \"recipient\")</b> of property and information regarding all operational procedures of <span class=\"paper_field\"></span>.</p>"
	dat += "<hr>"
	dat += "<p><b>I . Confidential Information.</b><br>The term \"Confidential Information\" means by any information which is proprietary to the Owner, whether or not owned or developed by the Owner, which is generally known other than by the Owner, which the Recipient may obtain through any direct or indirect contact with the owner, regardless of whether specifically identified as confidential or proprietary, Confidential Information shall include any information provided by the Owner concerning the business, technology and information of the Owner and any third party with which the owner deals, including, without limitation, business records and plans, trade secrets, technical data, product are ideas, contracts, financial information, pricing structure, health discounts, computer programs, listings and unknown wildlife, are all copyright and intellectual property. The nature of the information and the manner of disclosure are such that a reasonable person would understand is confidential.</p>"
	dat += ""
	dat += "<p><b>A. \"Confidential Information\" does not include:</b><br>- Matters of public knowledge that result from disclosure by the Owner.<br>- Information rightfully received by the recipient from a third party without a duty of confidentiality.<br>- Information disclosed by operation contract of The Company.<br>- Information disclosed by the recipient with the prior written consent of the Owner, and any other information that both parties agree in writing is not confidential.</p>"
	dat += "<hr>"
	dat += "<p><b>II. PROTECTION OF CONFIDENTIAL INFORMATION.</b><br> The recipient understands and acknowledges that the Confidential Information has been developed or obtained by the owner of The Company by Investment of Significant time, effort and expense, and that the Confidential Information is valuable, special and a unique asset of the Owner which provides the Owner with significant competitive advantage, and needs to be protected from improper disclosure. In consideration for the receipt by the Recipient of the confidential Information, the Recipient agrees as follows:</p>"
	dat += ""
	dat += "<p><b>A. No Disclosure.</b><br> The recipient will hold the confidential information in confidence and will not disclose the Confidential information to any person or entity without the prior written consent of the Owner.</p>"
	dat += ""
	dat += "<p><b>B. No copying/Modifying.</b><br> The Recipient will not copy or modify any Confidential Information to any person or entity without the prior written consent of the Owner.</p>"
	dat += ""
	dat += "<p><b>C. Unauthorized Use.</b><br> The Recipient shall promptly advise the Owner if the Recipient becomes aware of any possible unauthorized disclosures or use of the Confidential Information.</p>"
	dat += ""
	dat += "<p><b>D. application to employees.</b><br> The Recipient shall not disclose any confidential Information to any employees of the Recipient, except those employees who are required to have the Confidential Information in order to perform jobs and duties in connection with the limited purpose of this Agreement. Each permitted employee to whom confidential information is disclosed shall sign a non-disclosure agreement substantially the same as this agreement at the request of the Owner.</p>"
	dat += "<hr>"
	dat += "<p><b>III . Unauthorized Disclosure of Information- Injunction.</b><br> If it appears that the Recipient has disclosed (or has threatened to disclose) Confidential Information in violation of this Agreement, the Owner shall be entitled to a injunction to restrain the Recipient from disclosing the Confidential Information in whole or in part. The owner shall not be prohibited by this provision from pursuing other remedies, including a claim for losses and damages.</p>"
	dat += "<hr>"
	dat += "<p><b>IV. Non-Circumvention.</b><br> For a period of five hundred (500) years after the end of the terms of this Agreement, the Recipient will not attempt to do business with or otherwise solicit any business contacts found or otherwise referred by owners to Recipient for the purpose of circumventing, the result of which shall be prevent the Owner from realizing or recognizing a profit, fees, or otherwise, without the specific written approval of the owner. If such circumvention shall occur the Owner shall be entitled to any Commissions due pursuant to this agreement or relating to such Transaction.</p>"
	dat += "<hr>"
	dat += "<p><b>V. Return of Confidential Information.</b><br> Upon the written request of the owner, the recipient shall return to the owner all written material containing the Confidential Information. The recipient shall also deliver to the owner written statements signed by the Recipient certifying that all materials have been returned within one (1) days of receipt of the request.</p>"
	dat += "<hr>"
	dat += "<p><b>VI . Relationship of Parties.</b><br> Neither party has an obligation under this agreement to purchase products by the owner under this claus you are free to purchase weapons within the owners inventory at the standard rate.</p>"
	dat += "<hr>"
	dat += "<p><b>VII. No Warranty.</b><br> The Recipient acknowledges and agrees that the Confidential Information is provided on an \"AS IS\" basis. THE OWNER MAKES NO WARRANTIES, EXPRESS OR IMPLIED WITH RESPECT TO THE CONFIDENTIAL INFORMATION AND HEREBY EXPRESSLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OR INJURIES OF MERCHANT-ABILITY AND FITNESS FOR A PARTICULAR PURPOSE. IN NO WAY SHALL THE OWNER BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES IN CONNECTION WITH OR ARISING OUT OF THE PERFORMANCE OR USE OF ANY PORTION OF THE CONFIDENTIAL INFORMATION. The Owner does not represent or warrant that any product or business plans disclosed to the Recipient will be marketed or carried out as disclosed, or at all. Any actions taken by the Recipient in response to the disclosure of the Confidential Information shall be solely at the risk of the Recipient.</p>"
	dat += "<hr>"
	dat += "<p><b>VIII. Limited License to use.</b><br> The Recipient Shall not acquire any intellectual property rights under this Agreement except the limited right to use as set forth above. The recipient acknowledges that, as between the Owner and the Recipient, the Confidential Information and all related copyrights and other intellectual property rights, are (and at all times will be) the property of the Owner, even if suggestions, comments, and/or ideas made by the Recipient are incorporated into the Confidential Information or related materials during the period of this Agreement.</p>"
	dat += "<hr>"
	dat += "<p><b>IX . Indemnity.</b><br> Each party agrees to defend, indemnify, and hold harmless the other party and its officers, directors, agents, affiliates, representatives, and employees from any and all third party claims, demands, liabilities, costs and expenses, including reasonable attorney fees provided by the Owner. costs and expenses resulting from the indemnifying party's material breach of any duty, representation, or warranty under this Agreement.</p>"
	dat += "<hr>"
	dat += "<p><b>X . TERM.</b><br> The obligations of this agreement shall survive 03/30/2293 from the Effective date or until the Owner sends the Recipient written notice releasing the Recipient from this Agreement. After that, the Recipient must continue to protect the confidential information that was received during the term of this agreement from unauthorized use or disclosure for a additional time of the Owners Choosing.</p>"
	dat += "<hr>"
	dat += "<p><b>XI. Signatories.</b><br> This Agreement shall be executed by the named corporate representative, on behalf of The Company, and the recipient's named representative, and delivered in the manner prescribed by law as of the date first written above.</p>"
	dat += "<p><b>A. The Company.</b><br>Date: <font face=\"Times New Roman\"><i>[time2text(REALTIMEOFDAY, "Day DD Month [GLOB.game_year]")]</i></font><br>Representative: <span class=\"paper_field\"></span><br>Title: <span class=\"paper_field\"></span><br>Signature: <span class=\"paper_field\"></span><br></p>"
	dat += "<p><b>B. The Recipient.</b><br>Date: <font face=\"Times New Roman\"><i>[time2text(REALTIMEOFDAY, "Day DD Month [GLOB.game_year]")]</i></font><br>Representative: <span class=\"paper_field\"></span><br>Rank: <span class=\"paper_field\"></span><br>Signature: <span class=\"paper_field\"></span><br></p>"
	dat += "</div> <!-- /message-body-text -->"
	dat += ""
	dat += "<div class=\"message-signature-text\">"
	dat += "<p class=\"disclaimer\">Our organization accepts no liability for the content of this missive, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.</p>"
	dat += "<p class=\"disclaimer\">This message and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. This message contains confidential information and is intended only for addressee, if you are not the aforementioned addressee you should not disseminate, distribute or copy this missive. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.</p>"
	dat += "</div> <!-- /message-signature-text -->"
	dat += ""
	dat += "</div> <!-- /width-container -->"
	dat += "</body>"




	contents = dat

/datum/prefab_document/wey_yu/liaison/nda_long/uscm
	preset_recipient = "the United States Colonial Marines"
	doc_code = "WY442-B"
