/datum/skills/civilian/corporate_liason
	name = "Civilian"
	skills = list(
		SKILL_CQC = SKILL_CQC_DEFAULT,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_ENDURANCE = SKILL_ENDURANCE_NONE,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
	)
