/// Skillsets for the hunter games mode

/// Hunter games survivor contestant.
/datum/skills/hunter_games // hardy, crafty, but not especially good shots. No MP cheese.
	name = "Hunted"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_ENGINEER = SKILL_ENGINEER_MAX,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MAX,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_OVERWATCH = SKILL_OVERWATCH_DEFAULT,
		SKILL_MEDICAL = SKILL_MEDICAL_MAX,
		SKILL_SURGERY = SKILL_SURGERY_MAX,
		SKILL_RESEARCH = SKILL_RESEARCH_MAX,
		SKILL_ANTAG = SKILL_ANTAG_MAX,
		SKILL_PILOT = SKILL_PILOT_DEFAULT,
		SKILL_POLICE = SKILL_POLICE_DEFAULT,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_MAX,
		SKILL_JTAC = SKILL_JTAC_MAX,
		SKILL_EXECUTION = SKILL_EXECUTION_MAX,
		SKILL_INTEL = SKILL_INTEL_MAX,
	)
