#define XENO_AI_DAMAGE_TIER_1 10 * XENO_UNIVERSAL_DAMAGEMULT
#define XENO_AI_DAMAGE_TIER_2 15 * XENO_UNIVERSAL_DAMAGEMULT
#define XENO_AI_DAMAGE_TIER_3 20 * XENO_UNIVERSAL_DAMAGEMULT

#define XENO_AI_SPECIAL_ATTACK_PROBABILITY 20

#define XENO_AI_SPEED_TIER_1 3
#define XENO_AI_SPEED_TIER_2 2

#define XENO_LESSER_BURROW_AMOUNT 5
#define XENO_LESSER_BURROW_SPAWN_QUEUE_TIME 5 SECONDS
#define XENO_LESSER_BURROW_SPAWN_TIME 5 MINUTES
#define XENO_LESSER_BURROW_MIN_DISTANCE 15
