/datum/prefab_document/uacqs/commissioner/New()
	var/datum/asset/asset = get_asset_datum(/datum/asset/simple/paper)
	var/dat = ""

	dat += "<body>"
	dat += "<style>"
	dat += "body {"
	dat += "margin:0 auto;"
	dat += "padding:0;"
	dat += "background-image: url('[asset.get_url_mappings()["background_dark_fractal.png"]]');"
	dat += "background-position: center;"
	dat += "background-color: #ffffff;"
	dat += "font-family: 'Courier New';"
	dat += "color: #ffffff;"
	dat += "}"
	dat += ""
	dat += "i {"
	dat += "color: #ffffff;"
	dat += "}"
	dat += ""
	dat += "p {"
	dat += "color: #ffffff;"
	dat += "}"
	dat += ""
	dat += "b {"
	dat += "color: #ffffff;"
	dat += "}"
	dat += ""
	dat += "#uscm-fax-logo {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += "#uscm-fax-logo img {"
	dat += "width: 200px;"
	dat += "margin-top: 5px;"
	dat += "margin-bottom: 0px;"
	dat += "opacity: 0.;"
	dat += "}"
	dat += ""
	dat += "#width-container {"
	dat += "width: 500px;"
	dat += "min-height:500px;"
	dat += "margin:0 auto;"
	dat += "margin-top: 10px;"
	dat += "margin-bottom: 10px;"
	dat += "padding-left: 20px;"
	dat += "padding-right: 20px;"
	dat += "}"
	dat += ""
	dat += ".message-header-text p {"
	dat += "text-align: center;"
	dat += "}"
	dat += ""
	dat += ".header-title {"
	dat += "font-size: 17px;"
	dat += "font-weight: 600;"
	dat += "margin-bottom: 0px;"
	dat += "color: #FF2E2E;"
	dat += "}"
	dat += ""
	dat += ".header-subtitle {"
	dat += "font-size: 15px;"
	dat += "text-transform: uppercase;"
	dat += "letter-spacing: 1.5px;"
	dat += "color: #FF2E2E;"
	dat += "margin-top: 4px;"
	dat += "}"
	dat += ""
	dat += ".message-body-text {"
	dat += "text-align: left;"
	dat += "font-size: 17px;"
	dat += "margin-bottom: 25px;"
	dat += "}"
	dat += ""
	dat += ".message-subdata-text{"
	dat += "font-size: 20px;"
	dat += "text-align: center;"
	dat += "margin-bottom: 20px;"
	dat += "color: #FF0000;"
	dat += "font-family: inherit;"
	dat += "}"
	dat += ""
	dat += ".message-signature-text {"
	dat += "text-align:right;"
	dat += "font-size:15px;"
	dat += "margin-bottom: 20px;"
	dat += "}"
	dat += ".message-signature-small {"
	dat += "text-align:right;"
	dat += "font-size:12px;"
	dat += "font-style: italic;"
	dat += "}"
	dat += ""
	dat += ".signature-name {"
	dat += "font-size: 20px;"
	dat += "font-weight: bolder;"
	dat += "text-decoration: underline;"
	dat += "margin-bottom: 0px;"
	dat += "}"
	dat += ""
	dat += ".signature-title{"
	dat += "font-size: 14;"
	dat += "color: #e49b0f;"
	dat += "text-transform: uppercase;"
	dat += "margin-top: -12px;"
	dat += "}"
	dat += ""
	dat += ".message-signature-small{"
	dat += "font-size: 11px;"
	dat += "font-style: italic;"
	dat += "line-height: 1.3;"
	dat += "margin-top: -6px;"
	dat += "}"
	dat += ""
	dat += ".disclaimer{"
	dat += "font-size: 11px;"
	dat += "color: #e49b0f;"
	dat += "}"
	dat += ""
	dat += ".subheading{"
	dat += "text-align: center;"
	dat += "margin-top: -10px;"
	dat += "margin-bottom: -10px;"
	dat += "}"
	dat += ""
	dat += ".sub-subheading{"
	dat += "text-align: center;"
	dat += "margin-top: -10px;"
	dat += "margin-bottom: -10px;"
	dat += "font-size:12px;"
	dat += "}"
	dat += ""
	dat += "</style>"
	dat += ""
	dat += "<div id=\"width-container\">"
	dat += "<div id=\"uscm-fax-logo\">"
	dat += "<img src='[asset.get_url_mappings()["logo_uscm.png"]]' alt=\"USCM Logo\"/>"
	dat += "</div>"
	dat += ""
	dat += "<!--Header Info here-->"
	dat += "<div class=\"message-header-text\">"
	dat += "<hr style=\"margin-top:5px; margin-bottom:15px;\">"
	dat += "<p class=\"header-title\">UA COMMISSION OF QUALITY AND STANDARDS</p>"
	dat += "<p class=\"header-subtitle\">NOTICE OF OBSERVATION</p>"
	dat += "<hr style=\"margin-top:5px; margin-bottom:15px;\">"
	dat += "<p class=\"message-subdata-text\">- AUTHORISED PERSONNEL ONLY -</p>"
	dat += "<hr style=\"margin-top:5px; margin-bottom:15px;\">"
	dat += "</div> <!-- /Heasder Info -->"
	dat += ""

	dat += "<div class=\"message-body-text\">"
	dat += "<p>"
	dat += "USS Almayer,"
	dat += "</p> "
	dat += "<p>"
	dat += "This missive is to inform you that a Commissioner of the United Americas Commission of Quality and Standards will be aboard your ship for the duration of your current mission."
	dat += "</p>"
	dat += "<p>"
	dat += "Our Commissioner will chiefly be remaining in their office and keeping out of your way, though they have been granted authority by UA Military Leadership to conduct reviews of personnel and actions aboard the ship."
	dat += "</p>"
	dat += "<p>"
	dat += "They have not been granted any legal exemptions or authority to enforce Marine or Civilian Law as their foremost purpose is that of observation and bureaucratic oversight."
	dat += "</p>"
	dat += "<p>"
	dat += "Regards,"
	dat += "</p>"

	dat += "</div> <!-- /message-body-text -->"
	dat += "<hr style=\"margin-bottom:10px; margin-top:10px;\">"
	dat += "<div class=\"message-signature-text\">"
	dat += "<p class=\"signature-name\">Miranda Jones</p>"
	dat += "<br/>"
	dat += "<p class=\"signature-title\">Secretary General</p>"
	dat += "<p class=\"message-signature-small\">United Americas Commission of Quality and Standards."
	dat += "<br/>"
	dat += "F31-D, Office 12, Merian Tower, New York</p>"
	dat += "<p>"
	dat += "Dictated but not read."
	dat += "</p>"
	dat += "</div> <!-- /message-signature-text -->"
	dat += "</div> <!-- /width-container -->"
	dat += "</body >"

	contents = dat
