/*
---------------------
CIA
---------------------
*/

/datum/skills/cia
	name = "CIA"
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
	)

/datum/skills/cia/field_agent
	name = "CIA Field Agent"
	additional_skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/datum/skills/cia/field_agent/senior
	name = "CIA Senior Field Agent"
	additional_skills = list(
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SNIPER,
	)

/datum/skills/cia/security_officer
	name = "CIA Security Officer"
	additional_skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
	)

/// GRS ///

/datum/skills/cia/global_response
	name = JOB_CIA_GRS_OPR
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/cia/global_response/medic
	name = JOB_CIA_GRS_MED
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/cia/global_response/engineer
	name = JOB_CIA_GRS_ENG
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_FIREARMS = SKILL_FIREARMS_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
	)

/datum/skills/cia/global_response/heavy
	name = JOB_CIA_GRS_HVY
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
	)

/datum/skills/cia/global_response/sniper
	name = JOB_CIA_GRS_SNP
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SNIPER,
	)

/datum/skills/cia/global_response/leader
	name = JOB_CIA_GRS_TL
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_MASTER,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
	)
