/*
---------------------
CIA
---------------------
*/

/datum/skills/cia
	name = "CIA"
	skills = list(
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
	)

/datum/skills/cia/field_agent
	name = "CIA Field Agent"
	additional_skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)

/datum/skills/cia/field_agent/senior
	name = "CIA Senior Field Agent"
	additional_skills = list(
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SNIPER,
	)
