/*
---------------------
MILITARY SURVIVORS
---------------------
*/
//Hardcore survivors with poor equipment and skills, prove you're the best of the best.

/datum/skills/military/survivor/forecon_standard
	name = "Reconnaissance Rifleman"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_techician
	name = "Reconnaissance Support Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_marksman
	name = "Reconnaissance Designated Marksman"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SCOUT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_smartgunner
	name = "Reconnaissance Smartgunner"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_sniper
	name = "Reconnaissance Sniper"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SNIPER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_squad_leader
	name = "Reconnaissance Squad Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_LEADERSHIP = SKILL_LEAD_SKILLED,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/army_standard
	name = "US Army Trooper"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/military/survivor/army_engineer
	name = "US Army Combat Engineering Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_CONSTRUCTION_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
	)

/datum/skills/military/survivor/army_medic
	name = "US Army Combat Medical Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/military/survivor/army_marksman
	name = "US Army Marksman"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREMAN_SKILLED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SCOUT,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/army_gunner
	name = "US Army Heavy Gunner"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREMAN_SKILLED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/military/survivor/army_sl
	name = "US Army Squad Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREMAN_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
	)

/datum/skills/military/survivor/usasf
	name = "USASF Ground Crew"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_ENGINEER_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
	)

/datum/skills/military/survivor/usasf/technician
	name = "USASF Technician"
	additional_skills = list (
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MAX,
	)

/datum/skills/military/survivor/usasf/security
	name = "USASF Security Defender"
	additional_skills = list (
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_FIREARM = SKILL_FIREARMS_SKILLED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_SKILLED,
	)

/datum/skills/military/survivor/usasf/medical
	name = "USASF Medical Staff"
	additional_skills = list (
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
	)

/datum/skills/military/survivor/usasf/officer
	name = "USASF Officer"
	additional_skills = list (
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_FIREARM = SKILL_FIREARMS_SKILLED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_LEAD = SKILL_LEAD_EXPERT,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)

/datum/skills/military/survivor/usasf/pilot
	name = "USASF Pilot"
	additional_skills = list (
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_FIREARM = SKILL_FIREARMS_SKILLED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
	)
