/*
---------------------
MILITARY SURVIVORS
---------------------
*/
//Hardcore survivors with poor equipment and skills, prove you're the best of the best.

/datum/skills/military/survivor/forecon_standard
	name = "Reconnaissance Rifleman"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_techician
	name = "Reconnaissance Support Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_marksman
	name = "Reconnaissance Designated Marksman"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SCOUT,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_smartgunner
	name = "Reconnaissance Smartgunner"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_sniper
	name = "Reconnaissance Sniper"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SNIPER,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_LEADERSHIP = SKILL_LEAD_NOVICE,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/military/survivor/forecon_squad_leader
	name = "Reconnaissance Squad Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_DEFAULT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_DEFAULT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)
