/datum/skills/gladiator
	name = "Gladiator"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
	)

/datum/skills/gladiator/champion
	name = "Gladiator Champion"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_LEADERSHIP = SKILL_LEAD_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
	)

/datum/skills/gladiator/champion/leader
	name = "Gladiator Leader"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER, //Spartacus!
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_JTAC = SKILL_JTAC_MASTER,
	)

/datum/skills/gladiator/legionary
	name = "Roman Legionary"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
	)

/datum/skills/gladiator/legionary/eaglebearer
	name = "Roman Eaglebearer"
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MAX,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
	)
