/*
---------------------
LACN Garrisoners
---------------------
*/
/datum/skills/lacn/standard
	name = "LACN Fusilier"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED, //glorified fobbit
	)


/datum/skills/lacn/MP
	name = "LACN MP"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
	)

/datum/skills/lacn/groundcrew
	name = "LACN Ground Crew"
	skills = list(
		SKILL_PILOT = SKILL_PILOT_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
	)

/datum/skills/lacn/vhccrew
	name = "LACN Vehicle Crewmen"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_SKILLED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
	)

/datum/skills/lacn/pilot
	name = "LACN Pilot"
	skills = list(
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_DOMESTIC = SKILL_DOMESTIC_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)
