/*
---------------------
SYNTHETIC
---------------------
*/

/datum/skills/synthetic
	name = "Synthetic"
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_NAVIGATIONS = SKILL_NAVIGATIONS_TRAINED,
	)

/datum/skills/colonial_synthetic
	name = SYNTH_COLONY
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
	)

/datum/skills/working_joe
	name = SYNTH_WORKING_JOE
	skills = list(
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER, //So they can fully use the Maintenance Jack
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
	)

/datum/skills/infiltrator_synthetic
	name = SYNTH_INFILTRATOR
	skills = list(
		SKILL_CQC = SKILL_CQC_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_MASTER,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_MASTER,
		SKILL_SURGERY = SKILL_SURGERY_EXPERT,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_FIREMAN = SKILL_FIREMAN_MAX,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_ANTAG = SKILL_ANTAG_AGENT,
	)
