

//Supply drop. Just docks and has a crapload of stuff inside.
/datum/emergency_call/supplies
	name = "Supply Drop"
	mob_max = 0
	mob_min = 0
	arrival_message = "Weyland-Yutani Automated Supply Drop 334-Q signal received. Docking procedures have commenced."
	probability = 0
	auto_shuttle_launch = TRUE

/datum/emergency_call/supplies/spawn_items()
	var/turf/drop_spawn
	var/list/choices = list(0,1,2,3,4,5,6)

	for(var/i = 1 to 4) //Spawns 4 random things.
		drop_spawn = get_spawn_point(TRUE)
		if(istype(drop_spawn))
			var/obj/structure/closet/crate/weapon/weapon = new(drop_spawn)
			switch(pick_n_take(choices))
				if(0)
					new /obj/item/weapon/gun/pistol/m4a3(weapon)
					new /obj/item/weapon/gun/pistol/m1911(weapon)
					new /obj/item/attachable/burstfire_assembly(weapon)
					new /obj/item/attachable/compensator(weapon)
					new /obj/item/attachable/extended_barrel(weapon)

				if(1)
					new /obj/item/weapon/gun/smg/m39(weapon)
					new /obj/item/weapon/gun/smg/m39(weapon)
					new /obj/item/ammo_magazine/smg/m39/extended(weapon)
					new /obj/item/ammo_magazine/smg/m39/extended(weapon)
					new /obj/item/ammo_magazine/smg/m39/ap(weapon)
					new /obj/item/ammo_magazine/smg/m39/ap(weapon)
					new /obj/item/ammo_magazine/smg/m39/ap(weapon)
					new /obj/item/attachable/stock/smg(weapon)
					new /obj/item/attachable/stock/smg(weapon)
					new /obj/item/attachable/verticalgrip(weapon)
					new /obj/item/attachable/verticalgrip(weapon)
				if(2)
					new /obj/item/weapon/gun/flamer(weapon)
					new /obj/item/weapon/gun/flamer(weapon)
					new /obj/item/ammo_magazine/flamer_tank(weapon)
					new /obj/item/ammo_magazine/flamer_tank(weapon)
				if(3)
					new /obj/item/explosive/plastic(weapon)
					new /obj/item/explosive/plastic(weapon)
					new /obj/item/explosive/plastic(weapon)
					new /obj/item/explosive/grenade/high_explosive/pmc(weapon)
					new /obj/item/explosive/grenade/high_explosive/pmc(weapon)
					new /obj/item/explosive/grenade/incendiary(weapon)
					new /obj/item/explosive/grenade/incendiary(weapon)
				if(4)
					new /obj/item/weapon/gun/rifle/m41a(weapon)
					new /obj/item/weapon/gun/rifle/m41a(weapon)
					new /obj/item/ammo_magazine/rifle/extended(weapon)
					new /obj/item/ammo_magazine/rifle/extended(weapon)
					new /obj/item/ammo_magazine/rifle/incendiary(weapon)
					new /obj/item/ammo_magazine/rifle/incendiary(weapon)
					new /obj/item/ammo_magazine/rifle/l42a/incendiary(weapon)
					new /obj/item/ammo_magazine/rifle/l42a/incendiary(weapon)
					new /obj/item/ammo_magazine/rifle/ap(weapon)
					new /obj/item/ammo_magazine/rifle/ap(weapon)
					new /obj/item/attachable/stock/rifle(weapon)
					new /obj/item/attachable/stock/rifle(weapon)
				if(5)
					new /obj/item/weapon/gun/shotgun/combat(weapon)
					new /obj/item/weapon/gun/shotgun/combat(weapon)
					new /obj/item/ammo_magazine/shotgun/incendiary(weapon)
					new /obj/item/ammo_magazine/shotgun/incendiary(weapon)
					new /obj/item/ammo_magazine/shotgun/flechette(weapon)
					new /obj/item/ammo_magazine/shotgun/flechette(weapon)
					new /obj/item/attachable/stock/tactical(weapon)
					new /obj/item/attachable/stock/tactical(weapon)
				if(6)
					new /obj/item/weapon/gun/rifle/lmg(weapon)
					new /obj/item/ammo_magazine/rifle/lmg(weapon)
					new /obj/item/ammo_magazine/rifle/lmg(weapon)
					new /obj/item/attachable/verticalgrip (weapon)
				if(7)
					new /obj/item/weapon/gun/rifle/l42a(weapon)
					new /obj/item/weapon/gun/rifle/l42a(weapon)
					new /obj/item/ammo_magazine/rifle/l42a/incendiary(weapon)
					new /obj/item/ammo_magazine/rifle/l42a/incendiary(weapon)
					new /obj/item/ammo_magazine/rifle/l42a/ap(weapon)
					new /obj/item/ammo_magazine/rifle/l42a/ap(weapon)
					new /obj/item/attachable/stock/carbine(weapon)
					new /obj/item/attachable/stock/carbine(weapon)
					new /obj/item/attachable/scope/mini_iff(weapon)
					new /obj/item/attachable/scope/mini_iff(weapon)
