//Skills

/datum/skills/honor_guard
	name = "Honor Guard"
	skills = list(
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_POWERLOADER = SKILL_POWERLOADER_DABBLING,
		SKILL_CQC = SKILL_CQC_MP,
		SKILL_SMGS = SKILL_SMGS_TRAINED,
		SKILL_RIFLES = SKILL_RIFLES_TRAINED,
		SKILL_SHOTGUNS = SKILL_SHOTGUNS_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED
	)

/datum/skills/honor_guard/vet
	name = "Honor Guard Verteran"
	skills = list(
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_POWERLOADER = SKILL_POWERLOADER_DABBLING,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT
	)

/datum/skills/honor_guard/spec
	name = "Honor Guard Specialist"
	skills = list(
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
		SKILL_POWERLOADER = SKILL_POWERLOADER_DABBLING,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_HEAVY_WEAPONS = SKILL_HEAVY_WEAPONS_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_TRAINED
	)

/datum/skills/honor_guard/lead
	name = "Honor Guard Squad Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI, //to fix CIC apc.
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_PLASTEEL,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_POLICE = SKILL_POLICE_FLASH,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_SMARTGUN = SKILL_SMART_TRAINED
	)

/datum/skills/mortar_crew
	name = "Mortar Crew"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ADVANCED,
		SKILL_LEADERSHIP = SKILL_LEAD_BEGINNER,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED
	)