#define XENO_CUSTOMIZATION_SHOW_ALL "Show All"
#define XENO_CUSTOMIZATION_SHOW_LORE_FRIENDLY "Show Lore Friendly"
#define XENO_CUSTOMIZATION_SHOW_NONE "Show None"

GLOBAL_LIST_INIT(xeno_customization_visibility_options, list(
	XENO_CUSTOMIZATION_SHOW_ALL,
	XENO_CUSTOMIZATION_SHOW_LORE_FRIENDLY,
	XENO_CUSTOMIZATION_SHOW_NONE,
))
