
/datum/skills/mech_pilot
	name = "Mech Crewman"
	skills = list(
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)
