# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: Auto Changelog
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
permissions:
  contents: write
jobs:
  auto_changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Generate App Token
      id: app-token-generation
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ steps.app-token-generation.outputs.token }}

    - name: Run auto changelog
      uses: actions/github-script@v6
      with:
        script: |
          const { processAutoChangelog } = await import('${{ github.workspace }}/tools/pull_request_hooks/autoChangelog.js')
          await processAutoChangelog({ github, context })
        github-token: ${{ steps.app-token-generation.outputs.token }}
