name: Generate web assets
on:
  push:
    branches:
    - master
jobs:
  generate_static_assets:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    runs-on: ubuntu-latest
    concurrency: gen-assets
    steps:
      - uses: actions/checkout@v3
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
      - name: Install SpacemanDMM
        run: bash tools/ci/install_spaceman_dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
          mkdir deploy
          mv dmdoc/ deploy/doc
          mv tgui/public/ deploy/assets
          touch deploy/.nojekyll
          echo docs.cm-ss13.com > deploy/CNAME
          echo "<!DOCTYPE html><html><head><meta http-equiv='refresh' content='0;url=https://docs.cm-ss13.com/docs' /></head><body></body></html>" > deploy/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: deploy
