# Checks that a pull request has the commits in required_commits.txt.
# This uses the required_commits.txt from master, so that you cannot mess it up with an old branch.
name: Check required commits
on:
  pull_request:
    branches:
    - master
    - main
jobs:
  check_required_commits:
    name: Check required commits
    runs-on: ubuntu-20.04
    concurrency:
      group: check_required_commits-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          path: base
      - name: Read required commits
        id: required_commits
        run: |
          REQUIRED_COMMITS=$(jq -nrRc '[inputs | capture("^(?<commit>[a-f0-9]+) = (?<name>.+)$") | .commit, .name] | @tsv' ./base/.github/required_commits.txt)
          echo $REQUIRED_COMMITS
          echo "required_commits=$REQUIRED_COMMITS" >> $GITHUB_ENV
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          # We want as much depth as possible, but fetch-depth: 0 also checks out all branches.
          fetch-depth: 9999999999999999
          path: pr
      - name: Check for required commits
        run: |
          chmod +x ./tools/check_required_commits.sh
          ./tools/check_required_commits.sh
        shell: bash
        working-directory: pr
        env:
          REQUIRED_COMMITS: ${{ env.required_commits }}
