name: Changelog Verification
on:
  pull_request_target:
    types: [edited]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: "Check for ACTION_ENABLER secret and pass true to output if it exists to be checked by later steps"
        id: value_holder
        env:
          ENABLER_SECRET: ${{ secrets.ACTION_ENABLER }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "::set-output name=ACTIONS_ENABLED::$SECRET_EXISTS"
      - name: Get The Script
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          wget "https://raw.githubusercontent.com/${{ github.repository }}/master/.github/verify_changelog.py"
      - name: Set up Python
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          python -m pip install --upgrade pip
          python -m pip install pygithub
          sudo apt-get install dos2unix
      - name: Verify Changelog
        id: verify_holder
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          output=$(python verify_changelog.py)
          echo "::set-output name=VERIFY_RESULT::$output"
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Note Missing Changelog
        if: steps.value_holder.outputs.ACTIONS_ENABLED && steps.verify_holder.outputs.VERIFY_RESULT == 1
        run: |
          echo "::notice ::No changelog detected"
      - name: Note Invalid Changelog
        if: steps.value_holder.outputs.ACTIONS_ENABLED && steps.verify_holder.outputs.VERIFY_RESULT == -1
        run: |
          echo "::error ::Changelog is invalid"
